### ISSUE TITLE
Not enough useful peers on max peers

### ISSUE THREAD

**Issue by frankisawesome** [hyperledger/besu#3624] opened 2022-03-23 01:32 UTC
### Description
Besu node stops importing blocks and showing 'not enough useful peers' when there are max peers
<img width="874" alt="screen_shot_2022-03-22_at_1 17 32_pm" src="https://user-images.githubusercontent.com/39414003/159622466-2ccda75e-5d5b-4592-a146-384b7a6e3285.png">

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
I'm not sure whether this is reproducible.
I observed on besu-ohio-nightly-fast-sync node (ConsenSys internal) around March 22 2022 - 13:16

**Expected behavior:** [What you expect to happen]
Bad peers are dropped

**Comment by shemnon** [comment] 2022-03-23 04:01
Please do not link ConsenSys internal documents to public issues.  Only ConsenSys maintainers can read them and it makes it hard for the community to particiapte.

**Comment by frankisawesome** [comment] 2022-03-23 04:13
> Please do not link ConsenSys internal documents to public issues. Only ConsenSys maintainers can read them and it makes it hard for the community to particiapte.

Thanks for catching this, I thought I was pasting the screenshot but instead pasted a slack link, I've also added a note on the mention of consensys managed instance.

**Comment by iamhsk** [comment] 2022-04-28 02:44
Closing this since it is not reproducible. We believe this may get resolved as part of issue #2689. If we see this problem again, we'll open a new issue.

**Closed by iamhsk** 2022-04-28 02:44 UTC
Labels: can't reproduce, peering
