### ISSUE TITLE
Intermittent acceptance test failure PrivGetPrivateTransactionAcceptanceTest

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#778] opened 2020-04-24 06:39 UTC
~~~
org.hyperledger.besu.tests.web3j.privacy.PrivGetPrivateTransactionAcceptanceTest > returnsTransaction FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt 
    Expecting Optional to contain a value but it was empty within 30 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:148)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:873)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:657)
        at org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:24)
        at org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt.verify(ExpectSuccessfulEthGetTransactionReceipt.java:35)
        at org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.verify(BesuNode.java:639)
        at org.hyperledger.besu.tests.web3j.privacy.PrivGetPrivateTransactionAcceptanceTest.returnsTransaction(PrivGetPrivateTransactionAcceptanceTest.java:56)

        Caused by:
        java.lang.AssertionError: 
        Expecting Optional to contain a value but it was empty.
            at org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt.lambda$verify$0(ExpectSuccessfulEthGetTransactionReceipt.java:35)
            at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:203)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
~~~

### Versions (Add all that apply)
1.4.5-SNAPSHOT (possibility on 1.4.4 master as well)

### Additional Information
Observed in various PRs intermittently in CircleCI and local build.

**Comment by lucassaldanha** [comment] 2020-05-07 03:47
After reviewing the code, I belive the problem isn't with the test itself but with our AT framework.

The test is doing the right thing, sending a tx and waiting for it to be mined. However, the tx never gets mined and our condition times out.

Locally, it runs successfully 100% of the time. And it takes about 5 to 6 seconds.

This is probably failing because of the instability in out ATs. I'll close this ticket for now.

**Closed by lucassaldanha** 2020-05-07 03:47 UTC
Labels: privacy
