### ISSUE TITLE
Implement `eth_maxPriorityFeePerGas` RPC method

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7112] opened 2024-05-16 08:16 UTC
### Description

Implement the  `eth_maxPriorityFeePerGas` RPC method as defined by the official specification https://ethereum.github.io/execution-apis/api-documentation/

**Comment by macfarla** [comment] 2024-05-16 21:56
some extra context in #5658

**Comment by fab-10** [comment] 2024-05-17 08:23
this feature it is already implement in GraphQL, so should be simple to expose it as RPC methods as well

**Comment by macfarla** [comment] 2024-06-11 06:39
closing as duplicate of #5658

**Closed by macfarla** 2024-06-11 06:39 UTC
