### ISSUE TITLE
Native currency withdraw using send,transfer and call is not working in smart contracts deployed in private network

### ISSUE THREAD

**Issue by GowthamParamasivam** [hyperledger/besu#3549] opened 2022-03-09 18:47 UTC
As a besu user, we have a private network, we have smart contracts deployed and function to withdraw the native currency on the smart contract, function as follows

`function withdrawCurrencyFromContract(address user, uint256 amount) external onlyOwner {
        require(user != address(0), "Address cant be zero address");
        require(amount <= address(this).balance, "Amount exceeds balance");
        address payable _owner = payable(user);        
        _owner.transfer(amount);
        emit CurrencyFromContractTransferred(user, amount);
    }`
    
    
I am getting errors in the private network, but when I run the same contract on the other public test nets (Rinkeby, Ropsten) networks there is no issue with this code. 

### **Steps to reproduce the bug**
1. Deploy any smart contract with the above-mentioned function in it.
2. Send some native currency/token to the smart contract deployed.
3. Try to call this function.

**Expected behavior:**
This should transfer the balance of native currency/token in the contract to the respective address.

**Actual behavior:**
The function call returns the error message as 'Execution reverted'.

### Versions (Add all that apply)
* Software version: besu/v22.1.1/linux-x86_64/oracle_openjdk-java-16
* Java version: openjdk 16 2021-03-16
* OS Name & Version: Ubuntu 20.04.3 LTS
* Kernel Version: Linux ip-10-0-100-135 5.11.0-1022-aws 23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud VM, type, size: [Amazon Web Services t2-large]

### Additional Information
The solidity compiler version used is 0.8.7

**Comment by macfarla** [comment] 2022-03-10 00:41
Hi there, to help us investigate this issue, it would be great if you could supply a mini repo which we can use to reproduce your scenario. The smart contracts deployed (looks like you're also using OpenZeppelin?), and instructions for how you're sending the transaction to the `withdrawCurrencyFromContract` function. 

Also - what's your besu setup - genesis file, config options - this is the main difference between testnets and your private network.

With execution reverted - you can enable the revert reason to get more info - it could be that the onlyOwner constraint is not satisfied.

Have you tried on other clients eg Ganache or Geth - if the same thing happens on other clients it's not a besu bug.

**Comment by GowthamParamasivam** [comment] 2022-03-10 02:52
Hi @macfarla, you can find the contract, genesis.json, and config.toml file used in the network in the [this repo](https://github.com/GowthamParamasivam/besu-withdraw-issue). For testing, we have removed all the constraints and tried only with that function but still the same issue.

For sending the transaction, we have tried through remix ide, truffle console, and blockscout explorer, tried in these 3 ways, but the same issue we are facing. 

As per your suggestion tried in the ganache client also there is no issue in ganache.

following is the debug console from the remix ide, of the issue we are facing
![image](https://user-images.githubusercontent.com/43418883/157578773-81fd580d-9ae5-4925-886c-039e1aae7e2a.png)

**Comment by macfarla** [comment] 2022-03-10 04:37
If you enable the revert reason do you get more info? https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#revert-reason-enabled

**Comment by GowthamParamasivam** [comment] 2022-03-10 05:36
After enabling the revert reason in config file, as you said 
tried the following methods for tracing the transaction
[trace_transaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#trace_transaction)

`{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : [ {
    "action" : {
      "callType" : "call",
      "from" : "0x52ecc43fd9fc0cc4daebc3130fb0afff0a71cf4c",
      "gas" : "0x2d6c68",
      "input" : "0x4e4891ee00000000000000000000000052ecc43fd9fc0cc4daebc3130fb0afff0a71cf4c000000000000000000000000000000000000000000000000002386f26fc10000",
      "to" : "0x929919ea8c400a1cba7390c03b646976e4d42a28",
      "value" : "0x0"
    },
    "blockHash" : "0xe7e98d8b25e38c7bf0dcf6569fa6119d526f30dc2fce4e9890db77f0884a1c7f",
    "blockNumber" : 217042,
    "error" : "Bad instruction",
    "subtraces" : 0,
    "traceAddress" : [ ],
    "transactionHash" : "0x976026d2209e26a773808bb736007591687571dc0cb3f6b1e7c6208b919d591f",
    "transactionPosition" : 0,
    "type" : "call"
  } ]`
  
  [eth_getTransactionReceipt](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_gettransactionreceipt)
  
  `{
  "jsonrpc" : "2.0",
  "id" : 53,
  "error" : {
    "code" : -32602,
    "message" : "Invalid params"
  }`
  
  [debug_traceTransaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#debug_tracetransaction)
  
  `{
  "jsonrpc" : "2.0",
  "id" : 1,
  "error" : {
    "code" : -32602,
    "message" : "Invalid params"
  }
}`

**Comment by GowthamParamasivam** [comment] 2022-03-10 06:00
@macfarla,  After enabling the revert reason in config file, as you said 
tried the following methods for tracing the transaction, the following are the results of the methods

[trace_transaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#trace_transaction)

`{{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : [ {
    "action" : {
      "callType" : "call",
      "from" : "0x52ecc43fd9fc0cc4daebc3130fb0afff0a71cf4c",
      "gas" : "0x2d6c68",
      "input" : "0x4e4891ee00000000000000000000000052ecc43fd9fc0cc4daebc3130fb0afff0a71cf4c000000000000000000000000000000000000000000000000002386f26fc10000",
      "to" : "0x929919ea8c400a1cba7390c03b646976e4d42a28",
      "value" : "0x0"
    },
    "blockHash" : "0xfdb1d1471577db369df9b3fa347025af86d9fcba9e531dc8dc90ac46c1457688",
    "blockNumber" : 217225,
    "error" : "Bad instruction",
    "subtraces" : 0,
    "traceAddress" : [ ],
    "transactionHash" : "0x052b65dd0af21af90c65e4bb2ccfdb53a13f9b4fdf2e444d2e10645b7567219e",
    "transactionPosition" : 0,
    "type" : "call"
  } ]
}`
  
  [eth_getTransactionReceipt](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_gettransactionreceipt)
  
  `{
  "jsonrpc" : "2.0",
  "id" : 53,
  "result" : {
    "blockHash" : "0xfdb1d1471577db369df9b3fa347025af86d9fcba9e531dc8dc90ac46c1457688",
    "blockNumber" : "0x35089",
    "contractAddress" : null,
    "cumulativeGasUsed" : "0x2dc6c0",
    "from" : "0x52ecc43fd9fc0cc4daebc3130fb0afff0a71cf4c",
    "gasUsed" : "0x2dc6c0",
    "effectiveGasPrice" : "0x15a796357cf4",
    "logs" : [ ],
    "logsBloom" : "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status" : "0x0",
    "to" : "0x929919ea8c400a1cba7390c03b646976e4d42a28",
    "transactionHash" : "0x052b65dd0af21af90c65e4bb2ccfdb53a13f9b4fdf2e444d2e10645b7567219e",
    "transactionIndex" : "0x0"
  }
}`
  
  [debug_traceTransaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#debug_tracetransaction)
  
  `{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "gas" : 3000000,
    "failed" : true,
    "returnValue" : "",
    "structLogs" : [ {
      "pc" : 0,
      "op" : "PUSH1",
      "gas" : 2976872,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 2,
      "op" : "PUSH1",
      "gas" : 2976869,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 4,
      "op" : "MSTORE",
      "gas" : 2976866,
      "gasCost" : 12,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 5,
      "op" : "PUSH1",
      "gas" : 2976854,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 7,
      "op" : "CALLDATASIZE",
      "gas" : 2976851,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 8,
      "op" : "LT",
      "gas" : 2976849,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 9,
      "op" : "PUSH2",
      "gas" : 2976846,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 12,
      "op" : "JUMPI",
      "gas" : 2976843,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 13,
      "op" : "PUSH1",
      "gas" : 2976833,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 15,
      "op" : "CALLDATALOAD",
      "gas" : 2976830,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 16,
      "op" : "PUSH1",
      "gas" : 2976827,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 18,
      "op" : "SHR",
      "gas" : 2976824,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 19,
      "op" : "DUP1",
      "gas" : 2976821,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 20,
      "op" : "PUSH4",
      "gas" : 2976818,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 25,
      "op" : "EQ",
      "gas" : 2976815,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 26,
      "op" : "PUSH2",
      "gas" : 2976812,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 29,
      "op" : "JUMPI",
      "gas" : 2976809,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 46,
      "op" : "JUMPDEST",
      "gas" : 2976799,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 47,
      "op" : "CALLVALUE",
      "gas" : 2976798,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 48,
      "op" : "DUP1",
      "gas" : 2976796,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 49,
      "op" : "ISZERO",
      "gas" : 2976793,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 50,
      "op" : "PUSH2",
      "gas" : 2976790,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 53,
      "op" : "JUMPI",
      "gas" : 2976787,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 58,
      "op" : "JUMPDEST",
      "gas" : 2976777,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 59,
      "op" : "POP",
      "gas" : 2976776,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 60,
      "op" : "PUSH2",
      "gas" : 2976774,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 63,
      "op" : "PUSH2",
      "gas" : 2976771,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 66,
      "op" : "CALLDATASIZE",
      "gas" : 2976768,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 67,
      "op" : "PUSH1",
      "gas" : 2976766,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 69,
      "op" : "PUSH2",
      "gas" : 2976763,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 72,
      "op" : "JUMP",
      "gas" : 2976760,
      "gasCost" : 8,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 372,
      "op" : "JUMPDEST",
      "gas" : 2976752,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 373,
      "op" : "PUSH1",
      "gas" : 2976751,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 375,
      "op" : "DUP1",
      "gas" : 2976748,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 376,
      "op" : "PUSH1",
      "gas" : 2976745,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 378,
      "op" : "DUP4",
      "gas" : 2976742,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 379,
      "op" : "DUP6",
      "gas" : 2976739,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 380,
      "op" : "SUB",
      "gas" : 2976736,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 381,
      "op" : "SLT",
      "gas" : 2976733,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 382,
      "op" : "ISZERO",
      "gas" : 2976730,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 383,
      "op" : "PUSH2",
      "gas" : 2976727,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 386,
      "op" : "JUMPI",
      "gas" : 2976724,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 390,
      "op" : "JUMPDEST",
      "gas" : 2976714,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 391,
      "op" : "DUP3",
      "gas" : 2976713,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 392,
      "op" : "CALLDATALOAD",
      "gas" : 2976710,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 393,
      "op" : "PUSH1",
      "gas" : 2976707,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 395,
      "op" : "PUSH1",
      "gas" : 2976704,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 397,
      "op" : "PUSH1",
      "gas" : 2976701,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 399,
      "op" : "SHL",
      "gas" : 2976698,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 400,
      "op" : "SUB",
      "gas" : 2976695,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 401,
      "op" : "DUP2",
      "gas" : 2976692,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 402,
      "op" : "AND",
      "gas" : 2976689,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 403,
      "op" : "DUP2",
      "gas" : 2976686,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 404,
      "op" : "EQ",
      "gas" : 2976683,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 405,
      "op" : "PUSH2",
      "gas" : 2976680,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 408,
      "op" : "JUMPI",
      "gas" : 2976677,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 412,
      "op" : "JUMPDEST",
      "gas" : 2976667,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 413,
      "op" : "SWAP5",
      "gas" : 2976666,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 414,
      "op" : "PUSH1",
      "gas" : 2976663,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 416,
      "op" : "SWAP4",
      "gas" : 2976660,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 417,
      "op" : "SWAP1",
      "gas" : 2976657,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 418,
      "op" : "SWAP4",
      "gas" : 2976654,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 419,
      "op" : "ADD",
      "gas" : 2976651,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 420,
      "op" : "CALLDATALOAD",
      "gas" : 2976648,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 421,
      "op" : "SWAP4",
      "gas" : 2976645,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 422,
      "op" : "POP",
      "gas" : 2976642,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 423,
      "op" : "POP",
      "gas" : 2976640,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 424,
      "op" : "POP",
      "gas" : 2976638,
      "gasCost" : 2,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 425,
      "op" : "JUMP",
      "gas" : 2976636,
      "gasCost" : 8,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 73,
      "op" : "JUMPDEST",
      "gas" : 2976628,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 74,
      "op" : "PUSH2",
      "gas" : 2976627,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 77,
      "op" : "JUMP",
      "gas" : 2976624,
      "gasCost" : 8,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 80,
      "op" : "JUMPDEST",
      "gas" : 2976616,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 81,
      "op" : "PUSH1",
      "gas" : 2976615,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 83,
      "op" : "PUSH1",
      "gas" : 2976612,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 85,
      "op" : "PUSH1",
      "gas" : 2976609,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 87,
      "op" : "SHL",
      "gas" : 2976606,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 88,
      "op" : "SUB",
      "gas" : 2976603,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 89,
      "op" : "DUP3",
      "gas" : 2976600,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 90,
      "op" : "AND",
      "gas" : 2976597,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 91,
      "op" : "PUSH2",
      "gas" : 2976594,
      "gasCost" : 3,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 94,
      "op" : "JUMPI",
      "gas" : 2976591,
      "gasCost" : 10,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 171,
      "op" : "JUMPDEST",
      "gas" : 2976581,
      "gasCost" : 1,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null
    }, {
      "pc" : 172,
      "op" : "INVALID",
      "gas" : 2976580,
      "gasCost" : 0,
      "depth" : 1,
      "stack" : null,
      "memory" : null,
      "storage" : null,
      "reason" : null,
      "error" : [ "INVALID_OPERATION" ]
    } ]
  }
}`

**Comment by GowthamParamasivam** [comment] 2022-03-10 07:40
@macfarla Thanks for your support

seems like SELFBALANCE opcode is not working, when compared with the traces from the other network. SELFBALANCE opcode has been introduced in istanbulfork,

 if I add istanbul fork block in chain config in the genesis file, Will I break any existing smart contracts in the network?

**Comment by macfarla** [comment] 2022-03-11 00:00
Ah - glad you found the issue! Changing the genesis file basically means you're starting a new chain. So you may have to start from block 0 and redeploy your contracts. But then they should work.

One question - was there an example that you followed in setting up this network? Wondering if we need to update some docs to recommend using later milestones.

**Comment by GowthamParamasivam** [comment] 2022-03-11 02:48
Actually, we have deployed a few contracts in the production environment, so I think we need to hard fork the network to Istanbul protocol. In that case, do I face any issues later? 

Regarding your question, We followed the genesis file from [here](https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/).

**Comment by macfarla** [comment] 2022-03-11 03:50
yes you can set the istanbul milestone to a particular block ie hardfork, as long as all your nodes have the same genesis that should be fine.

I'll close this ticket - let us know if you have any further issues.

**Closed by macfarla** 2022-03-11 03:50 UTC
Labels: bug, P3
