### ISSUE TITLE
Besu aborting zombie backend queries frequently

### ISSUE THREAD

**Issue by ColinCampbell** [hyperledger/besu#4293] opened 2022-08-23 00:28 UTC
Hi there! I recently started using Besu (initially on version 22.7.0) as an execution client alongside Teku. I've been running into issues with Besu aborting queries from Teku as "Zombie backend query detected" under both 22.7.0 and the recently released 22.7.1 which I'm running as of a few hours ago. Teku is on version 22.8.1 so both clients should have the mainnet merge configuration.

This issue seems distinct from #4221 given this is occurring for many types of queries, including simpler ones like getBlock rather than more complex ones like the deposit log queries. I am also running the version of Teku with the fix for #4221 (https://github.com/ConsenSys/teku/pull/6061).

Logs and the docker compose configuration are in [this gist](https://gist.github.com/ColinCampbell/4eba6579efba0d3b905124e0a9e0adea).

`iostat` and Grafana monitoring shows that I/O seems pretty reasonable (averages around 3.5%, spiking to 28% or so every few minutes).

### Steps to Reproduce (Bug)
This doesn't seem very reproducible given other people don't seem to be running into this, but what I've done is:
1. Clone eth-docker and set up using Besu
2. Fully sync Besu using X_CHECKPOINT (provided by eth-docker)
3. See these Zombie backend query issues.

This has persisted across restarting the services in question and restarting the staking computer.

**Expected behavior:** Besu should  be responding to queries from Teku

**Actual behavior:** Lots of log output saying that queries are being killed.

**Frequency:** All the time as far as I can tell.

### Versions (Add all that apply)
* Software version: besu/v22.7.1/linux-x86_64/openjdk-java-11
* Java version: openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
* OS Name & Version: Ubuntu 20.04.4 LTS
* Kernel Version: `Linux 8b5bccac605d 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Docker Version: 20.10.12

### Additional Information
* System info - AMD Ryzen 7 4800U (8 cores, 1.8 GHz base clock, 4.2 GHz boost). 64 GB RAM. Samsung 970 EVO Plus 2TB SSD.
* Besu setup info - This is the command which ends up executing Besu, full docker-compose is in the gist linked above:
```
docker-entrypoint.sh /opt/besu/bin/besu --data-path /var/lib/besu --p2p-port 58932 --rpc-http-enabled --rpc-http-api WEB3,ETH,NET --rpc-http-host 0.0.0.0 --rpc-http-port 8545 --rpc-http-cors-origins=* --rpc-http-max-active-connections=65536 --rpc-ws-enabled --rpc-ws-api WEB3,ETH,NET --rpc-ws-host 0.0.0.0 --rpc-ws-port 8546 --max-peers 25 --fast-sync-min-peers 5 --host-allowlist=* --engine-host-allowlist=* --engine-jwt-secret=/var/lib/besu/ee-secret/jwtsecret --engine-rpc-port=8551 --logging info --network mainnet --metrics-enabled --metrics-host 0.0.0.0 --metrics-port 6060 --data-storage-format=BONSAI --sync-mode=X_CHECKPOINT
```
My Besu setup is pretty much vanilla from eth-docker. JWT token is set up and Teku reports using the execution engine for its connection to the execution client. I'm using non-default P2P ports for both Besu and Teku. Command starting Teku is here:
```
docker-entrypoint.sh /opt/teku/bin/teku --data-path=/var/lib/teku --log-destination=CONSOLE --network=mainnet --ee-endpoint=http://execution:8551 --ee-jwt-secret-file /var/lib/teku/ee-secret/jwtsecret --p2p-port=61991 --p2p-peer-upper-bound=100 --p2p-peer-lower-bound=90 --validators-keystore-locking-enabled=true --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords --validators-graffiti=eth-docker --logging=info --rest-api-host-allowlist=* --rest-api-enabled=true --rest-api-interface=0.0.0.0 --rest-api-port=5052 --metrics-enabled=true --metrics-port=8008 --metrics-interface=0.0.0.0 --metrics-host-allowlist=* --validator-api-enabled=true --validator-api-port=7500 --validator-api-host-allowlist=* --validator-api-cors-origins=* --validator-api-keystore-file=/var/lib/teku/teku-keyapi.keystore --validator-api-keystore-password-file=/var/lib/teku/teku-keyapi.password --validators-proposer-default-fee-recipient=REDACTED
```

EDIT: My Besu data is taking up 398GB of space, is this expected? From some Discord messages and some documentation I can find online this seems too small?

**Comment by JeffOnGithub** [comment] 2022-08-23 17:37
Same here on an up to date vanilla setup of eth-docker

**Comment by ColinCampbell** [comment] 2022-08-23 18:46
> Same here on an up to date vanilla setup of eth-docker

@JeffOnGithub did you restart your Besu instance during its initial sync, by chance? I took mine down while restarting the staking computer and I'm wondering if that could have caused this issue

**Comment by JeffOnGithub** [comment] 2022-08-23 19:30
I did restart it at least once as i'm currently trying out eth-docker. 
I also have the same ''looks a bit small'' situation on Besu at around 400GB too.

**Comment by ColinCampbell** [comment] 2022-08-23 19:38
I found some discussion on Discord late last night that implies ~400GB should be expected for an X_CHECKPOINT sync so that might not be related.

I'm wondering if Besu restarting during the sync is what caused the issues. I might resync and see if I can keep it up the whole time but I'm weary of doing that without knowing that's what caused the problem.

**Comment by JeffOnGithub** [comment] 2022-08-23 19:52
I just did a ./ethd terminate to restart from the ground up.
I'll keep the checkpoint sync and resync without touching anything to see if i end up with a working situation.
I'll keep the post updated.

**Comment by ColinCampbell** [comment] 2022-08-24 19:55
@JeffOnGithub how did the sync go?

**Comment by JeffOnGithub** [comment] 2022-08-24 22:24
It completed like 20 minutes ago and so far i'm not seeing any errors in the logs (teku and besu). 

So far, the delete everything, resync and don't touch anything seems to work.

**Comment by ColinCampbell** [comment] 2022-08-24 23:33
Thanks for the info. Will try the same.

**Comment by ColinCampbell** [comment] 2022-08-25 00:31
So, bizarrely, it seems like it's mended itself without needing to resync. I took Teku offline to provide it with an Infura `eth1-endpoint` flag so it could receive blocks while Besu was resyncing. When I started Teku back up and checked the Besu logs one last time before removing its docker volume, there were no more Zombie query warnings. 

https://gist.github.com/ColinCampbell/982d5d28ebb3bd9b5984f0c00f76c835

These are the most recent logs. I took Teku offline at roughly 00:10:25 UTC. Here are the full Besu logs since I started it a couple of days ago if anyone is curious. 

https://gist.github.com/ColinCampbell/804a5133e91b2c14b8d9ba2bede31886

I'm going to keep monitoring, somewhat skeptical of it, but Besu might have healed itself at some point?

**Comment by JeffOnGithub** [comment] 2022-08-25 00:39
Your idea that restarting caused the issue seems right. I just did a ./etd restart and the zombie process warning just started popping up in execution logs.

**Comment by ColinCampbell** [comment] 2022-08-25 00:45
Oh dang, that's a huge bummer. GIven Teku seems to be falling back on Infura it looks like I'll need to do a resync, but maybe I'll use X_SNAP and see if that works?

**Comment by JeffOnGithub** [comment] 2022-08-27 16:45
Looks like it's working with a new install and snap sync.

Since it's running in docker, i don't think it's the new install that solved the issue, i think it's maybe more about Checkpoint sync creating a partial database that can't be used for a consensus client?

**Comment by ColinCampbell** [comment] 2022-08-27 22:33
I'm not sure to be honest. I doubt the new install fixed it, my guess is something seems to be broken with checkpoint syncing at the moment. Thanks for the update and I'll try an X_SNAP sync myself.

**Comment by remyroy** [comment] 2022-08-30 15:28
I've just had something similar happen to me with Besu (`besu/v22.7.1/linux-x86_64/openjdk-java-17`) configured to run under a systemd service with:

```ini
[Unit]
Description=Besu Ethereum Client (Mainnet)
After=network.target
Wants=network.target

[Service]
User=besu
Group=besu
Type=simple
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/besu/bin/besu \
    --network=mainnet \
    --sync-mode=X_CHECKPOINT \
    --rpc-http-enabled=true \
    --engine-rpc-port=8551 \
    --engine-host-allowlist=localhost,127.0.0.1 \
    --data-path=/var/lib/besu \
    --data-storage-format=BONSAI \
    --metrics-enabled=true \
    --engine-jwt-secret=/var/lib/ethereum/jwttoken

[Install]
WantedBy=default.target
```

Besu could not recover after a reboot. It would keep showing `WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process` messages.

Here is the full logs: https://gist.github.com/remyroy/c87862a87c7bfe0515b914c66b8227a3

**Comment by JeffOnGithub** [comment] 2022-08-30 19:56
> I've just had something similar happen to me with Besu (`besu/v22.7.1/linux-x86_64/openjdk-java-17`) configured to run under a systemd service with:
> 
> ```ini
> [Unit]
> Description=Besu Ethereum Client (Mainnet)
> After=network.target
> Wants=network.target
> 
> [Service]
> User=besu
> Group=besu
> Type=simple
> Restart=always
> RestartSec=5
> ExecStart=/usr/local/bin/besu/bin/besu \
>     --network=mainnet \
>     --sync-mode=X_CHECKPOINT \
>     --rpc-http-enabled=true \
>     --engine-rpc-port=8551 \
>     --engine-host-allowlist=localhost,127.0.0.1 \
>     --data-path=/var/lib/besu \
>     --data-storage-format=BONSAI \
>     --metrics-enabled=true \
>     --engine-jwt-secret=/var/lib/ethereum/jwttoken
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Besu could not recover after a reboot. It would keep showing `WARN | BackendQuery | Zombie backend query detected [ unnamed ], aborting process` messages.
> 
> Here is the full logs: https://gist.github.com/remyroy/c87862a87c7bfe0515b914c66b8227a3
> 
> Maybe Besu failed to properly stop because it needs more time to shutdown than the default systemd service allows for? I'll resync from scratch and add a `TimeoutStopSec=180` to that systemd service definition to test it out.

Looks like my first failed correction try. When you use Checkpoint Sync, after the completion it don't throw errors as long as you don't restart Besu. 

I did a clean ./ethd restart after the checkpoint sync (while Besu was not throwing errors) and got the errors right after. So it's not because of a ''failed stop'' that you got that.

**Comment by remyroy** [comment] 2022-08-30 20:06
@JeffOnGithub Are you saying you believe it silently fails during the initial checkpoint sync but that failure is only visible after a restart? If that's the case, it might be worth looking at my logs again to see if anything special came up during my initial sync.

**Comment by ColinCampbell** [comment] 2022-08-30 20:47
I just saw these messages on Discord which may or may not be related to this issue, it does mention restarts causing Besu to need to resync:
https://discord.com/channels/905194001349627914/938504958909747250/1013053097842581504

**Comment by ColinCampbell** [comment] 2022-08-31 02:04
> I did a clean ./ethd restart after the checkpoint sync (while Besu was not throwing errors) and got the errors right after. So it's not because of a ''failed stop'' that you got that.

Could this be the same timeout issue manifesting in a different situation? Docker gives services a default of 10 seconds to shut down, and if they aren't done by then it will SIGKILL. It could be that Besu just happened to get killed within 10 seconds in some cases and in other cases it could SIGKILLed leading to a corrupted DB.

I had to restart Besu during the final parts of my X_SNAP sync for what seems like a different/recoverable issue. I made sure to use `docker-compose stop --timeout 900 execution` to give it more than enough time to gracefully shut off, and it definitely took longer than 10 seconds. Will report back once it's fully synced to see if I've avoided the Zombie query issue or not

**Comment by ColinCampbell** [comment] 2022-08-31 02:26
Well, the `besu.yml` file in `eth-docker` specifies a `stop_grace_period` of 3 minutes. I'm 99% sure when I killed Besu during my sync I would have brought it down using `docker-compose stop execution` to ensure that the validator kept running, which might have been my undoing. Not sure if `docker-compose stop` would reference the service definition or just go with the default 10 seconds from the command line. If you guys were using `./ethd down` or equivalent then the timeout issue is likely not causing the Zombie queries

**Comment by ColinCampbell** [comment] 2022-08-31 04:54
After restarting Besu during the last part of the X_SNAP sync, it picked up syncing and finished. It seems to be working fine across restarts and Teku can connect to it just fine. It seems like my issues could have been (a) restarting during the initial sync which seems to be an undocumented big no-no and/or (b) no allowing for a longer timeout when stopping the docker container.

**Comment by remyroy** [comment] 2022-08-31 16:39
I just did some more tests. I resynced from scratch on Mainnet using checkpoint sync. Everything went fine. I was even able to restart with no issue. However, I soon as I rebooted my machine, I got the `WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - getBlockBody ], aborting process.` messages again and my Teku client would complain about Besu not being in sync or being down.

Here are the full logs of this second try: https://gist.github.com/remyroy/aa2156d12b51a7784785a3b45234f7ce
You can see the restart at around `2022-08-31 16:08:10` and the full reboot at around `2022-08-31 16:24:33`

**Comment by ahamlat** [comment] 2022-09-01 10:07
I'm trying to reproduce, meanwhile, @ColinCampbell @remyroy could you share TCP connections graph if you have the grafana node exporter dashboard ?
From my understanding, Besu received JSON RPC calls and when processing these calls, the underlying connections were closed. It could be also related to Max Open file descriptors, it you have a low limit.

**Comment by remyroy** [comment] 2022-09-01 13:26
Here is my TCP connections graph from 2022-08-31 16:00:00 to 2022-08-31 17:00:00 during when I did a restart and a reboot for my second try. I'm mainly running a besu+teku combo on that machine:

![tcp-connections](https://user-images.githubusercontent.com/303593/187925197-b87ba53e-6d55-453a-9342-5f8866e0482f.png)


Here are my hard and soft limits for open file descriptors:
```
$ ulimit -Hn
1048576
$ ulimit -Sn
1024
```

**Comment by remyroy** [comment] 2022-09-01 16:02
I've updated my systemd service file to this:

```ini
[Unit]
Description=Besu Ethereum Client (Mainnet)
After=network.target
Wants=network.target

[Service]
User=besu
Group=besu
Type=simple
Restart=always
RestartSec=5
TimeoutStopSec=180
LimitNOFILE=8388608
ExecStart=/usr/local/bin/besu/bin/besu \
    --network=mainnet \
    --sync-mode=X_CHECKPOINT \
    --rpc-http-enabled=true \
    --engine-rpc-port=8551 \
    --engine-host-allowlist=localhost,127.0.0.1 \
    --data-path=/var/lib/besu \
    --data-storage-format=BONSAI \
    --metrics-enabled=true \
    --engine-jwt-secret=/var/lib/ethereum/jwttoken

[Install]
WantedBy=default.target
```

That LimitNOFILE should help with the open file descriptors limit. I'll let you know if it helps.

**Comment by ahamlat** [comment] 2022-09-02 19:56
Unfortunately, I wasn't able to reproduce after several restarts, I will keep trying. I had only one "Zombie" log line.
(https://gist.github.com/ahamlat/a07aa4b462bfd66fd894a6023a1b199d)

**Comment by remyroy** [comment] 2022-09-03 11:37
It does not seem related to open file descriptors limits. Even with `LimitNOFILE=8388608` in my service file, I still get a bunch of `Zombie backend query detected [ unnamed ], aborting process` messages in my logs after rebooting once Besu is fully in sync and Besu becomes unsuable for Teku.

**Comment by ahamlat** [comment] 2022-09-05 12:45
I copied your configuration and did several tests, I still cannot reproduce. I'm running Teku inside docker and besu directly on the VM (without docker).
Could you please enable ADMIN RPC methods (--rpc-http-api=ADMIN ), call this RPC method and share Besu logs
```
curl -X POST --data '{"jsonrpc":"2.0", "method":"admin_changeLogLevel", "params":["DEBUG", ["org.hyperledger.besu.ethereum.api.jsonrpc"]], "id":1}' http://127.0.0.1:8545
```

**Comment by remyroy** [comment] 2022-09-05 13:10
> I copied your configuration and did several tests, I still cannot reproduce. I'm running Teku inside docker and besu directly on the VM (without docker).
> Could you please enable ADMIN RPC methods (--rpc-http-api=ADMIN ), call this RPC method and share Besu logs
> ```
> curl -X POST --data '{"jsonrpc":"2.0", "method":"admin_changeLogLevel", "params":["DEBUG", ["org.hyperledger.besu.ethereum.api.jsonrpc"]], "id":1}' http://127.0.0.1:8545
> ```

I've switched to another execution client in preparation for the merge. I'm also running memtest86+ to rule out a memory module issue on that machine. I might be able to perform this test and additional ones after the merge.

**Comment by jonson** [comment] 2022-09-05 13:12
I was hit by this one too, with both X_CHECKPOINT and X_SNAP.  I initially did a sync with X_CHECKPOINT and based on the comments, blew it away and redid a sync with X_SNAP.  Both imported fine, but my CL client (teku) was having issues with requests to besu (resulting in these zombie logs).  I put in a mitm proxy to debug the actual json-rpc calls that were failing, and tracked it down to teku misbehaving.  I don't think the teku bug was properly fixed.  Here's an example of one of the requests that was getting killed:

```
{
    "id": 56,
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "address": [
                "0x00000000219ab540356cBB839Cbe05303d7705Fa"
            ],
            "fromBlock": "0xaf858c",
            "toBlock": "0xafac9c",
            "topics": [
                "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
            ]
        }
    ]
}
```

And the wall time for this request is ~11.5s: `0.02s user 0.05s system 0% cpu 11.493 total` 

During the initial deposit contract log querying, with the default teku settings, my response was taking 10-12s, triggering at timeout in teku.  The block range wasn't being decreased, so the same requests were being tried over and over (I lost my mitm logs here, will re-post in the teku ticket).

For anyone else experiencing this (and using teku), try setting this value: https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#eth1-deposit-contract-max-request-size  to something smaller (1000, or even 100).  It might take another ~60m to sync.  I immediately stopped getting the zombie log messages after this.

**Comment by jonson** [comment] 2022-09-05 16:15
I was able to reproduce this on a brand new teku VM (talking to the same besu sync'd instance).  Once the first request starts failing here (due to the timeout), it keeps retrying the same 10k block range.  Each of the getLogs requests have the same payload, the range is not changing:

```
{
    "id": 4346,
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "address": [
                "0x00000000219ab540356cBB839Cbe05303d7705Fa"
            ],
            "fromBlock": "0xac9f72",
            "toBlock": "0xacc682",
            "topics": [
                "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
            ]
        }
    ]
}
```


```
>>> 0xacc682 - 0xac9f72
10000
```

![Screenshot 2022-09-05 at 12-04-00 mitmproxy](https://user-images.githubusercontent.com/406373/188487343-01931565-35e0-4574-aa27-e1084e506a98.png)

We should probably open this as a new issue in the teku repo?  For now at least updating the docs to suggest a lower range would probably save headaches as people are trying to sync.

For hardware, if it matters, I'm running on a 8th gen i7 with plenty of ram (12gb allocated to besu, 14gb to teku) and each are running on separate VMs, backed by separate nvme drives.

**Comment by ahamlat** [comment] 2022-09-05 18:49
Really appreciate the feedback @jonson, are using Eth-docker stack ? 
I was wondering if there is any proxy between Teku and Besu ? Which tool do you use to display these RPC calls ?

**Comment by jonson** [comment] 2022-09-05 19:47
I'm happy to help!

I am running besu on a dedicated debian VM (debian 11), and the same with teku, using systemd to launch them.  I have a pretty simple besu config:

```
color-enabled=false

network="mainnet"
data-path="/srv/besu"
data-storage-format="BONSAI"


rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["*"]
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"

host-allowlist=["*"]
engine-host-allowlist=["*"]
engine-rpc-port=8550
engine-jwt-secret="/etc/besu/token.txt"

sync-mode="X_SNAP"
```

To debug I'm running [http proxy](https://mitmproxy.org/), which I launch on my desktop via docker-compose:

```
version: '3'

services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    entrypoint: "mitmweb --web-host 0.0.0.0"
    ports:
      - "8080:8080"
      - "8081:8081"
```

This starts the proxy on port 8080 and the web-ui on 8081.  I then tweak my teku config to use a http proxy by passing the flags `-Dhttp.proxyHost=10.81.81.105 -Dhttp.proxyPort=8080` when launching it,  where `10.81.81.105` is where I'm running the mitmproxy.  Here's the systemd service:

```
[Unit]
Description=teku
Wants=network-online.target
After=network-online.target

[Service]
User=teku
Group=teku
Type=simple
Restart=always
RestartSec=5
StandardOutput=append:/var/log/teku/teku.log
StandardError=append:/var/log/teku/teku.log
#Environment="JAVA_OPTS=-Xmx14g -Dhttp.proxyHost=10.81.81.105 -Dhttp.proxyPort=8080"
Environment="JAVA_OPTS=-Xmx14g"
ExecStart=/usr/bin/teku --config-file=/etc/teku/teku.yaml
  
[Install]
WantedBy=multi-user.target
```

On the teku machine, a command like `http_proxy=http://10.81.81.105:8080/ curl http://example.com/` ensures the proxy is working correctly (this request shows up in the web-ui), then start up teku and watch the requests start to flow in.  I only added this http proxy to debug the issue, I normally have teku directly talking to besu.

**Comment by ajsutton** [comment] 2022-09-05 23:11
> @ajsutton On Teku side, do you think [the auto adjusting behaviour ](https://github.com/ConsenSys/teku/blob/ce6e13e32f2c5029aa05895f400c00a9c72a3f38/beacon/pow/src/main/java/tech/pegasys/teku/beacon/pow/DepositFetcher.java#L90)of the batch size should fix this issue ?

The auto-adjusting behaviour is fixed in teku and people are still seeing this issue a lot so I'd say not.  The nodes I was seeing it on are no longer having any issue now that the back off is fixed, but it's still showing up persistently for a lot of people so seems to be an issue somewhere.

**Comment by Kengcong711** [comment] 2022-09-06 15:15
I am also getting these from Besu. This started after updating to 22.7.1 - Besu and 22.8.1 - Teku.
Currently on 22.9.0 - Teku.


Sep 06 15:09:08 stakercong besu[107442]: 2022-09-06 15:09:08.032+00:00 | vert.x-worker-thread-17 | WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process.
Sep 06 15:09:18 stakercong besu[107442]: 2022-09-06 15:09:18.033+00:00 | vert.x-worker-thread-14 | WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process.
Sep 06 15:09:28 stakercong besu[107442]: 2022-09-06 15:09:28.034+00:00 | vert.x-worker-thread-19 | WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - getBlockBody ], aborting process.
Sep 06 15:09:38 stakercong besu[107442]: 2022-09-06 15:09:38.035+00:00 | vert.x-worker-thread-14 | WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - getBlockBody ], aborting process.

I wiped Besu DB and resync'd after the first time it happened and that seemed to have resolved it for a week. Now the issue is occurring again. Let me know if you need anything from me to review.

**Comment by jonson** [comment] 2022-09-06 21:32
Try adding this flag to teku `--eth1-deposit-contract-max-request-size=1000` and see if it goes away (https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#eth1-deposit-contract-max-request-size).

**Comment by ahamlat** [comment] 2022-09-07 13:00
I was going to suggest the same thing, @Kengcong711 : have you had a chance to test this workaround ?

**Comment by Kengcong711** [comment] 2022-09-07 13:54
I will give this a try. I restarted Teku and the issue has not recurred yet. I will apply this change and report back if it reoccurs. Thanks!

**Comment by ngmi-dev** [comment] 2022-09-09 04:18
I had the same issue and adding `--eth1-deposit-contract-max-request-size=1000` to teku appeared to fix the issue. Further reboots of both besu/teku did not trigger the `Execution Client is offline` error in teku logs.

**Comment by ahamlat** [comment] 2022-09-09 06:51
@Kengcong711 did you notice the issue from your last feedback ?

**Comment by Kengcong711** [comment] 2022-09-09 12:46
I have not seen the issue occur after the change. But please note I don't have a way to test if it's resolved. It occurred seemingly random.

**Comment by ahamlat** [comment] 2022-09-09 14:13
@ColinCampbell, could you close the issue as putting this teku flag --eth1-deposit-contract-max-request-size=1000 seems to resolve the issue. 
@ColinCampbell @remyroy @jonson @ngmi-dev @Kengcong711 : please don't hesitate to re-open this issue if the "Zombie" logs appear again

**Closed** 2022-09-13 00:54 UTC
Labels: mainnet, 22.7.2
