### ISSUE TITLE
Uncaught DNS exception

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#1648] opened 2020-12-02 01:27 UTC
Catch this exception (DNS) and log something sensible

```
2020-12-02 11:25:19.097+10:00 | main | INFO  | DefaultP2PNetwork | Starting DNS discovery with URL enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
2020-12-02 11:25:19.186+10:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /[0:0:0:0:0:0:0:0]:30303.
2020-12-02 11:25:19.187+10:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2020-12-02 11:25:19.227+10:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2020-12-02 11:25:19.228+10:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /[0:0:0:0:0:0:0:0]:30303
2020-12-02 11:25:19.260+10:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://5d3a1a80d81b081b0925757ae07a4352c944808f077c060e7acde4c167ed8002d66f242c3c3520acc9cd2d3d93045820f933ae0eb08ab3d10f2365e6ac8ab72c@127.0.0.1:30303
2020-12-02 11:25:19.261+10:00 | main | INFO  | DefaultP2PNetwork | Node address 0x22584f7c247a67c0047832c0e429359b96f41c2d
2020-12-02 11:25:19.265+10:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2020-12-02 11:25:19.265+10:00 | main | INFO  | FastSyncDownloader | Starting fast sync.
2020-12-02 11:25:19.269+10:00 | main | INFO  | WaitForPeersTask | Waiting for 5 peers to connect. 0 peers currently connected.
2020-12-02 11:25:19.280+10:00 | main | INFO  | Runner | Ethereum main loop is up.
2020-12-02 11:25:19.285+10:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2020-12-02 11:25:19.286+10:00 | main | INFO  | LogBloomCacheMetadata | Lookup cache metadata file in data directory: /Users/sallymacfarlane/workspace/besu/build/install/besu/caches
2020-12-02 11:25:20.002+10:00 | nioEventLoopGroup-3-3 | INFO  | WaitForPeersTask | Waiting for 4 peers to connect.
2020-12-02 11:25:34.490+10:00 | Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
java.net.SocketTimeoutException
	at org.xbill.DNS.Resolver.send(Resolver.java:156)
	at org.apache.tuweni.discovery.DNSResolver.resolveRecordRaw(DNSResolver.kt:149)
	at org.apache.tuweni.discovery.DNSResolver.resolveRecord(DNSResolver.kt:72)
	at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:166)
	at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
	at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
	at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
	at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:129)
	at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:105)
	at org.apache.tuweni.discovery.DNSResolver.collectAll(DNSResolver.kt:94)
	at org.apache.tuweni.discovery.DNSTimerTask.run(DNSDaemon.kt:70)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

### Steps to Reproduce (Bug)
1. `besu`

**Expected behavior:** expected no exceptions when starting besu with default config

**Actual behavior:** uncaught exception as above

**Frequency:** running besu with default network (mainnet) or rinkeby or ropsten

### Versions (Add all that apply)
➜  besu-local-nodes git:(multi-tenancy) ✗ besu --version
2020-12-02 11:29:12,324 main INFO Registered Log4j as the java.util.logging.LogManager.
besu/v20.10.2-dev-784d8a96/osx-x86_64/oracle_openjdk-java-14

**Comment by macfarla** [comment] 2020-12-02 01:31
This doesn't happen with this JDK version:
➜  besu-local-nodes git:(multi-tenancy) ✗ besu --version
2020-12-02 11:31:08,370 main INFO Registered Log4j as the java.util.logging.LogManager.
besu/v20.10.2-dev-784d8a96/osx-x86_64/oracle_openjdk-java-11

**Comment by atoulme** [comment] 2020-12-02 02:09
This is odd. It signifies the DNS server didn't respond in a timely manner and the request to the DNS server timed out.
It looks like an issue worth investigating and fixing.

**Comment by atoulme** [comment] 2020-12-02 02:21
Do you reproduce this always? Or is it intermittent?

**Comment by macfarla** [comment] 2020-12-04 00:50
It happens for me always, if I am using JDK 14

**Comment by atoulme** [comment] 2020-12-04 00:58
Thank you. I am tracking and looking to fix this issue.

**Comment by shemnon** [comment] 2020-12-09 17:56
I would be satisfied with a single log line instead of a stack trace.  A full fix would be great, but may be unworkable if the DNS is problematic (such as wrong address or the DNS provider blocks that resolution).

**Comment by timbeiko** [comment] 2021-01-13 17:36
@atoulme are you still working on this? No worries if not, we'll just unassign you. Thanks!

**Comment by atoulme** [comment] 2021-01-14 02:52
Yes, I have issued a fix for this in Apache Tuweni and the fix is in the upcoming release.

**Comment by vmichalik** [comment] 2021-05-24 14:28
Hey @atoulme, can you confirm if this is resolved?

**Comment by atoulme** [comment] 2021-05-24 15:36
It’s fixed in the next release which is not released yet.

**Comment by vmichalik** [comment] 2021-05-24 15:38
Excellent news

**Closed** 2021-06-15 17:15 UTC
