### ISSUE TITLE
Besu crash on mainnet

### ISSUE THREAD

**Issue by PacoBits** [hyperledger/besu#4765] opened 2022-12-02 11:45 UTC
This started with upgrade to version 22.10.1
It  happends each time we restart. Some times take more time, but always crash
We have tried with param       --Xbonsai-use-snapshots=false but also crash

I attach the trace.
```
Description

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fb738ace941, pid=1, tid=238

 JRE version: OpenJDK Runtime Environment (11.0.17+8) (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
 Java VM: OpenJDK 64-Bit Server VM (11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 C  [libc.so.6+0x22941]  abort+0x213

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/besu/core.1)

 If you would like to submit a bug report, please visit:
   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
```

[besu_02122022.log](https://github.com/hyperledger/besu/files/10140765/besu_02122022.log)

**Comment by garyschulte** [comment] 2022-12-03 17:11
@PacoBits would you upgrade to the latest 22.10.2 release and confirm/disconfirm that it has fixed this issue for you

**Comment by ziobox** [comment] 2022-12-04 16:48
> @PacoBits would you upgrade to the latest 22.10.2 release and confirm/disconfirm that it has fixed this issue for you

with latest 22.10.2 inside a containerized rocketpool, I have the same issue

```
rocketpool_eth1  | ####################################################################################################
rocketpool_eth1  | #                                                                                                  #
rocketpool_eth1  | # Besu 22.10.2                                                                                     #
rocketpool_eth1  | #                                                                                                  #
rocketpool_eth1  | # Configuration:                                                                                   #
rocketpool_eth1  | # Network: Mainnet                                                                                 #
rocketpool_eth1  | # Data storage: Bonsai                                                                             #
rocketpool_eth1  | # Sync mode: Checkpoint                                                                            #
rocketpool_eth1  | # RPC HTTP APIs: ETH,NET,WEB3                                                                      #
rocketpool_eth1  | # RPC HTTP port: 8545                                                                              #
rocketpool_eth1  | # Engine APIs: ENGINE,ETH                                                                          #
rocketpool_eth1  | # Engine port: 8551                                                                                #
rocketpool_eth1  | #                                                                                                  #
rocketpool_eth1  | # Host:                                                                                            #
rocketpool_eth1  | # Java: openjdk-java-17                                                                            #
rocketpool_eth1  | # Maximum heap size: 7.84 GB                                                                       #
rocketpool_eth1  | # OS: linux-x86_64                                                                                 #
rocketpool_eth1  | # glibc: 2.31                                                                                      #
rocketpool_eth1  | # Total memory: 31.33 GB                                                                           #
rocketpool_eth1  | # CPU cores: 12                                                                                    #
rocketpool_eth1  | #                                                                                                  #
rocketpool_eth1  | ####################################################################################################
rocketpool_eth1  | pure virtual method called
rocketpool_eth1  | terminate called without an active exception
rocketpool_eth1  | #
rocketpool_eth1  | # A fatal error has been detected by the Java Runtime Environment:
rocketpool_eth1  | #
rocketpool_eth1  | #  SIGSEGV (0xb) at pc=0x00007f60a9d58941, pid=1, tid=219
rocketpool_eth1  | #
rocketpool_eth1  | # JRE version: OpenJDK Runtime Environment (17.0.5+8) (build 17.0.5+8-Ubuntu-2ubuntu120.04)
rocketpool_eth1  | # Java VM: OpenJDK 64-Bit Server VM (17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
rocketpool_eth1  | # Problematic frame:
rocketpool_eth1  | # C  [libc.so.6+0x22941]  abort+0x213
rocketpool_eth1  | #
rocketpool_eth1  | # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/besu/core.1)
rocketpool_eth1  | #
rocketpool_eth1  | # An error report file with more information is saved as:
rocketpool_eth1  | # /opt/besu/hs_err_pid1.log
rocketpool_eth1  | pure virtual method called
rocketpool_eth1  | terminate called recursively
rocketpool_eth1  | pure virtual method called
rocketpool_eth1  | terminate called recursively
rocketpool_eth1  | #
rocketpool_eth1  | # If you would like to submit a bug report, please visit:
rocketpool_eth1  | #   Unknown
rocketpool_eth1  | # The crash happened outside the Java Virtual Machine in native code.
```

**Comment by garyschulte** [comment] 2022-12-04 17:06
Thanks, will try to reproduce.  What version of rocketpool stack are you on?

**Comment by ahamlat** [comment] 2022-12-04 17:15
@PacoBits Could you share the content of this file /opt/besu/hs_err_pid1.log ?

**Comment by ziobox** [comment] 2022-12-04 17:27
> Thanks, will try to reproduce. What version of rocketpool stack are you on?

Rocket Pool client version: 1.7.0
Rocket Pool service version: 1.7.0
Selected Eth 1.0 client: Besu (Locally managed)
	Image: hyperledger/besu:22.10.2-openjdk-latest
Selected Eth 2.0 client: Teku (Locally managed)
	Image: consensys/teku:22.11.0

**Comment by PacoBits** [comment] 2022-12-04 17:29
We upgraded to 22.10.2 and crashed again. 
We have not  /opt/besu/hs_err_pid1.log because its running in docker and we need to restart the service as soon as possible. 
Currently running on 22.10.0 and no crash. 
[besu_03122022.log](https://github.com/hyperledger/besu/files/10149108/besu_03122022.log)

**Comment by ahamlat** [comment] 2022-12-04 17:44
Thanks, is this log (besu_03122022.log) related to 22.10.2 or 22.10.1 ? 
Because I see Java 17 in the error reported above and the log is related to node with Java 11.
The crash we've fixed in 22.10.2 happens usually in  C  [librocksdbjni ...] lib, the crash you're fixing seems to be another variant 
```
# JRE version: OpenJDK Runtime Environment (11.0.16+8) (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni5187014992309245782.so+0x2d04ca] ```

**Comment by ahamlat** [comment] 2022-12-04 17:54
Another interesting point here @garyschulte is the number of cores, I see 16 cores in the crash log file, this means CompletableFuture,runAsync will run 15 threads, worth testing this particular case.

**Comment by PacoBits** [comment] 2022-12-04 19:13
besu_03122022.log  is  22.10.2 version. 
We are running besu with oficial docker imagen.

**Comment by ahamlat** [comment] 2022-12-05 08:52
We're investigating this case.

**Comment by garyschulte** [comment] 2022-12-09 00:50
This seems to have been an interaction between bonsai snapshot archive flag (`--Xbonsai-use-snapshots=true`) enabled by default in rocketpool 1.7.0 and a race condition where querying for eth_getBlockByNumber for the `latest` block would cause a segfault if worldstate storage had been recently truncated when starting a X_SNAP or X_CHECKPOINT sync.

**Comment by ruigil** [comment] 2022-12-09 14:15
The same happened to me on Goerli but with another problematic frame, related to rocksdb

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f16fdba1fcb, pid=1, tid=210
#
# JRE version: OpenJDK Runtime Environment (17.0.5+8) (build 17.0.5+8-Ubuntu-2ubuntu120.04)
# Java VM: OpenJDK 64-Bit Server VM (17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni14646062180189647216.so+0x83cfcb]  rocksdb::WriteBatchEntryComparator::GetComparator(rocksdb::ColumnFamilyHandle const*) const+0xb
#
# Core dump will be written. Default location: /opt/besu/core
```

**Closed** 2023-02-17 21:54 UTC
