### ISSUE TITLE
Besu IBFT1 no longer syncs with latest GoQuorum

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#3387] opened 2022-02-07 23:42 UTC
(moved from https://github.com/ConsenSys/PEEPS/issues/95)

The IBFT1 test checks that Besu can sync a IBFT 1 chain with GoQuorum and relay transactions is no longer passing after the latest GoQuorum update.

This is an example of the test failure

https://app.circleci.com/pipelines/github/ConsenSys/PEEPS/655/workflows/fa17ffb2-8e01-46f4-acb6-3fca53999a0e/jobs/1669/tests

note: The test in PEEPs is temporarily ignored whilst this is under investigation

**Comment by jframe** [comment] 2022-02-15 00:19
This is caused by a change in GoQuorum implementation of istanbul/99 sub protocol. This will be fixed on the GoQuorum side.

**Closed by jframe** 2022-02-15 00:19 UTC
Labels: bug, TeamGroot, P3
