### ISSUE TITLE
CORS Origin error when connecting Metamask to besu private network

### ISSUE THREAD

**Issue by YounesBM** [hyperledger/besu#3299] opened 2022-01-18 12:51 UTC
Hello,

I'm trying to deploy besu in a "prod" environment on Azure Kubernetes, from this repository : 
https://github.com/ConsenSys/quorum-kubernetes

All pods are running, but since a few days, I am unable to connect Metamask to my private network. Here are the error logs I'm experiencing:

On Metamask:

![Metamask Connection](https://github.com/YounesBM/logs-quorum/blob/main/Metamask%20network.JPG?raw=true)

On my private network :
    
`kubectl logs besu-node-member-1-0 -c member-1-besu --namespace besu`

![Member-1 logs](https://github.com/YounesBM/logs-quorum/blob/main/Metamask.JPG?raw=true)

I have created a repository to reproduce the bug in question:
https://github.com/YounesBM/besu-metamask-issue

Do you have any idea how to fix this error?

Best regards,

Younes

**Comment by cheul123a** [comment] 2022-01-19 00:32
same.

**Comment by macfarla** [comment] 2022-01-19 01:37
The fix for this is https://github.com/hyperledger/besu/pull/3296 
We will be cutting a release 21.10.9 tomorrow which will include this hotfix.

**Comment by YounesBM** [comment] 2022-01-19 16:14
Hello @cheul123a @macfarla,

Thank you for your feedback.

I will keep an eye on your releases to try again after your hotfix.

Best Regards,

Younes

**Comment by macfarla** [comment] 2022-01-19 22:54
@YounesBM @cheul123a  Besu Release 21.10.9 is complete! This has two fixes: CORS-origin fix to allow MetaMask to connect (regression since upgrading vert.x) and fix for ethFeeHistory accepting hex values for blockCount. More details and download links here - https://github.com/hyperledger/besu/releases/tag/21.10.9

Please confirm that this fixes your issue and we can close this ticket :)

**Comment by YounesBM** [comment] 2022-01-20 09:55
Hello,

Everything works perfectly!

Thank you again for your responsiveness :)

Best regards,

Younes

**Comment by macfarla** [comment] 2022-01-20 17:56
@YounesBM Great news! Thanks for verifying. I will close this ticket.

**Closed by macfarla** 2022-01-20 17:56 UTC

**Comment by hlloreda** [comment] 2022-02-04 23:26
Hello,

It appears that I'm currently facing the same problem with the Docker images (hyperledger/besu:21.10.9), which seems odd since I do not encounter this problem if I download the binary and run it myself. Do you have any idea what might be causing this on the Docker images?

Best regards

**Comment by macfarla** [comment] 2022-02-07 23:46
@hlloreda the docker image for hyperledger/besu:21.10.9 should definitely contain the same code as downloading the 21.10.9 binary and running it. Docker does a pretty good job of caching, my guess would be that something is cached somewhere. If you are stuck on this, can you please open a new ticket and give us more details? Thanks
