### ISSUE TITLE
Besu world state download pipeline cancelled due to RocksDB Busy exception.

### ISSUE THREAD

**Issue by wcgcyx** [hyperledger/besu#4901] opened 2023-01-10 03:31 UTC
### Description
At the moment, the world state sync would hangs if besu encounters RocksDB busy exception as it breaks the pipeline. Especially when using forest data format - I'm getting this after enabling DEBUG logging:
```
{"@timestamp":"2023-01-06T02:40:19,785","level":"DEBUG","thread":"EthScheduler-Services-8 (batchPersistStorageData)","class":"Pipeline","message":"Unhandled exception in pipeline. Aborting.","throwable":" org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
    at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:350)
    at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java:49)
    at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$1.commit(SegmentedKeyValueStorageAdapter.java:119)
    at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage$Updater.commit(WorldStateKeyValueStorage.java:211)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.lambda$doPersist$0(StorageRangeDataRequest.java:97)
    at org.hyperledger.besu.ethereum.trie.CommitVisitor.maybeStoreNode(CommitVisitor.java:72)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie$1.maybeStoreNode(StackTrie.java:125)
    at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:63)
    at org.hyperledger.besu.ethereum.trie.LeafNode.accept(LeafNode.java:79)
    at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
    at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
    at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
    at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
    at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
    at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
    at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.commit(StoredMerklePatriciaTrie.java:170)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie.commit(StackTrie.java:119)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.doPersist(StorageRangeDataRequest.java:102)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.SnapDataRequest.persist(SnapDataRequest.java:101)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.PersistDataStep.persist(PersistDataStep.java:59)
    at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$8(SnapWorldStateDownloadProcess.java:264)
    at org.hyperledger.besu.services.pipeline.MapProcessor.processNextInput(MapProcessor.java:31)
    at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
    at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.rocksdb.RocksDBException: Busy
    at org.rocksdb.Transaction.commit(Native Method)
    at org.rocksdb.Transaction.commit(Transaction.java:208)
    at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:344)
    ... 28 more"}
```
I've attempted a fix here: 
https://github.com/hyperledger/besu/compare/main...wcgcyx:besu:forest-sync-rocksdb-retry?expand=1 
This addressed any busy exception during sync but ideally this could be done in rocksdb level so the retry mechanism works for anywhere in the codebase. 

### Acceptance Criteria
* Besu recovers from database busy exception (e.g. retry after busy) and continues sync.

### Steps to Reproduce (Bug)
1. Start besu on mainnet with FOREST data format (snap sync, checkpoint sync or fast sync) with DEBUG logging

**Expected behavior:** [What you expect to happen]
Besu finishes syncing.

**Actual behavior:** [What actually happens]
World state download cancelled when busy exception is thrown and besu never finishes syncing.

**Frequency:** [What percentage of the time does it occur?]
Almost every time on my machine.

### Versions (Add all that apply)
* Software version: [22.10.3 and 23.1.0-beta]

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - mainnet
* System info - MacBook Pro 2021, CPU: M1 Pro, Memory: 32GB

**Comment by non-fungible-nelson** [comment] 2023-01-26 14:52
@ahamlat - any opinion on the PR linked above?

**Comment by ahamlat** [comment] 2023-01-26 18:56
The issue here seems to be more related to FOREST implementation. We had "Busy" exceptions in the past on BONSAI as well but IIRC we haven't had this exception recently as it should be fixed.
Regarding FOREST, Zhenyang suggests a workaround to catch the "busy" exception and try again, retryAttempts times. Ideally, we would do the same work as BONSAI to fix concurrency issues but I'm not sure that FOREST is used a lot. So depending on our priorities, we can imagine three options
1. Do nothing, as we're pushing for BONSAI instead of FOREST
2. Create the workaround if the issue is still reported by users
3. Take more time to study the concurrency issues and resolve them

**Comment by gfukushima** [comment] 2023-06-13 22:27
Closing this as it's been fixed by https://github.com/hyperledger/besu/pull/5328

**Closed by gfukushima** 2023-06-13 22:27 UTC
Labels: syncing, forest
