### ISSUE TITLE
Check Besu on LegacyTest Random94

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#1217] opened 2020-07-13 11:23 UTC
Besu seems unable to process this test.

```
./retesteth -t LegacyTests/Constantinople/BlockchainTests/ValidBlocks/bcStateTests -- --all --clients "besu" --singletest "randomStatetest94"
```

```
Running randomStatetest94_Byzantium
Request: {"jsonrpc":"2.0","method":"test_setChainParams","params":[{
    "params" : {
        "homesteadForkBlock" : "0x00",
        "EIP150ForkBlock" : "0x00",
        "EIP158ForkBlock" : "0x00",
        "byzantiumForkBlock" : "0x00"
    },
    "accounts" : {
        "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
            "balance" : "0x0de0b6b3a7640000",
            "code" : "0x44444243204555",
            "nonce" : "0x00",
            "storage" : {
            }
        },
        "0x945304eb96065b2a98b57a48a06ae28d285a71b5" : {
            "balance" : "0x2e",
            "code" : "0x6000355415600957005b60203560003555",
            "nonce" : "0x00",
            "storage" : {
            }
        },
        "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
            "balance" : "0x084595161401484a000000",
            "code" : "0x",
            "nonce" : "0x00",
            "storage" : {
            }
        }
    },
    "sealEngine" : "NoProof",
    "genesis" : {
        "author" : "0x945304eb96065b2a98b57a48a06ae28d285a71b5",
        "difficulty" : "0x020000",
        "gasLimit" : "0x7fffffffffffffff",
        "extraData" : "0x42",
        "timestamp" : "0x03e8",
        "nonce" : "0x0102030405060708",
        "mixHash" : "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
    }
}],"id":1}
Reply: {
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : true
}
Request: {"jsonrpc":"2.0","method":"test_importRawBlock","params":["0xf90272f90202a0bda2b7e466e793f456294003aee1e702d77e89d852c3d8aa0c1971877356bacaa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794945304eb96065b2a98b57a48a06ae28d285a71b5a0ee8f47d40d4a9ad58736a2a2b9efa1c76fc67dc0bb3af11fc4da90ccff738f05a074bf1dc886ea419650c420eab7ad6b89d4227d5450b369fdbd8f6ca305c43106a0b778de832730579f58ea453863efb04ee3a88e7399989ac99ea6223a483290a6b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008302000001887fe0000000000001860449e8c0a3dd845db6f82180a00000000000000000000000000000000000000000000000000000000000000000880000000000000000f86af8688001887effffffffffffff94095e7baea6a6c7c4c2dfeb977efac326af552d87830186a0421ba04c2cdd77d6f05279603e0f2106bff4a0e515e0886a7f9776c663188d68e5f256a0769f54af0f4518bb7b6511d5412c7e288f42bd68bfc5f5a34838787a6cb1cb2fc0"],"id":2}
Reply: 
Error: Expected field 'id' not found in config: rpcCall_response (req: '{"jsonrpc":"2.0","method":"test_importRawBlock","params":["0xf90272f90')
{} (bcStateTests/randomStatetest94_Byzantium, fork: Byzantium, block: 0)


```

**Comment by shemnon** [comment] 2020-07-13 15:25
That random state test is exceedingly heavy on the sha3 calls, which we are still using Java crypto for.  If you increase the timeouts it will pass.

**Comment by shemnon** [comment] 2020-07-13 15:26
It's already on the native crypto todo list - https://github.com/hyperledger/besu-native/issues/20

**Comment by winsvega** [comment] 2020-07-15 10:42
The call return empty {} json instantly.
Increasing timeouts doesn't help

**Comment by shemnon** [comment] 2020-07-15 14:23
It shouldn't return empty json ever, we should be throwing exceptions and closing the HTTP channel before we send empty data. that may be how retesteth is interpreting a closed channel.  

Locally I get successful runs.  So my guess is that this is something in the transport layer.

Can you crank up the logging on the besu node and share the besu logs in a gist?  `--logging=debug` as the CLI option.  The next level is `--logging=TRACE` but if it gets into the EVM it is quite verbose

**Comment by winsvega** [comment] 2020-07-16 21:31
debug log
```
2020-07-16 23:28:35.764+02:00 | vert.x-eventloop-thread-1 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 127.0.0.1:47710
2020-07-16 23:30:48.029+02:00 | vert.x-eventloop-thread-1 | DEBUG | Recycler | -Dio.netty.recycler.maxCapacityPerThread: 4096
2020-07-16 23:30:48.030+02:00 | vert.x-eventloop-thread-1 | DEBUG | Recycler | -Dio.netty.recycler.maxSharedCapacityFactor: 2
2020-07-16 23:30:48.030+02:00 | vert.x-eventloop-thread-1 | DEBUG | Recycler | -Dio.netty.recycler.linkCapacity: 16
2020-07-16 23:30:48.030+02:00 | vert.x-eventloop-thread-1 | DEBUG | Recycler | -Dio.netty.recycler.ratio: 8
2020-07-16 23:30:48.047+02:00 | vert.x-eventloop-thread-1 | DEBUG | AbstractByteBuf | -Dio.netty.buffer.checkAccessible: true
2020-07-16 23:30:48.047+02:00 | vert.x-eventloop-thread-1 | DEBUG | AbstractByteBuf | -Dio.netty.buffer.checkBounds: true
2020-07-16 23:30:48.049+02:00 | vert.x-eventloop-thread-1 | DEBUG | ResourceLeakDetectorFactory | Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@3d3c873d
2020-07-16 23:30:48.096+02:00 | vert.x-eventloop-thread-1 | DEBUG | ZlibCodecFactory | -Dio.netty.noJdkZlibDecoder: false
2020-07-16 23:30:48.096+02:00 | vert.x-eventloop-thread-1 | DEBUG | ZlibCodecFactory | -Dio.netty.noJdkZlibEncoder: false
2020-07-16 23:30:48.180+02:00 | vert.x-worker-thread-0 | DEBUG | JsonRpcHttpService | JSON-RPC request -> test_setChainParams
2020-07-16 23:30:48.270+02:00 | vert.x-worker-thread-0 | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Byzantium: 0]
2020-07-16 23:30:48.615+02:00 | vert.x-worker-thread-1 | DEBUG | JsonRpcHttpService | JSON-RPC request -> test_importRawBlock
```

besu instance just exit

**Comment by shemnon** [comment] 2020-07-20 21:43
The next line should be some variant of...
```
2020-07-20 15:36:51.933-06:00 | vert.x-worker-thread-1 | TRACE | EVM | Depth: 0
Operation: SHA3
PC: 4
Gas cost: 4715484021607
Gas Remaining: 9151314442816826795
Depth: 0
Stack:
	0 0x38335dc6a80d9d82607a3e36ad614d619c0f601ec37fe2facea8e5fd183a4f15
	1 0x0000000000000000000000000000000000000000000000000000000000020000
	2 0x0000000000000000000000000000000000000000000000000000000000020000
```

Which the two inputs were asking to Keccak hash 1.5 Gigs of basically zeros.  I'm thinking we may be running into memory issues on the client and exiting with out of memory as we hash the entire byte array instead of streaming the memory.

How big a box do you have retesteth running on?

**Comment by winsvega** [comment] 2020-07-20 22:11
16 gig. At least 10 should be allocatable

**Comment by shemnon** [comment] 2020-07-20 22:49
Transaction is valid per the EVM.  The other possibility is that it takes too long for the SHA3 to calculate before retesteth gets impatient.  Could be another candidate for `--lowcpu`

**Comment by shemnon** [comment] 2020-07-20 22:50
If it was memory I would expect logs somewhere, either in the besu log or wherever in the system the oom killer logs its results.

**Comment by winsvega** [comment] 2020-07-20 23:11
It can't be lowcpu. I run on 3.4 GHz. 
Is test_mineblocks is synchronous. Retesteth waits untill 10 minute timeout.

But the besu client crash in an instant.

**Comment by shemnon** [comment] 2020-07-20 23:22
Not able to reproduce.

**Comment by shemnon** [comment] 2020-07-20 23:22
10 minutes should be more than enough.  What's the box you are running on, an amazon t3? what linux distro?  This is weird.

**Comment by winsvega** [comment] 2020-07-21 22:21
I am debugging locally. Ubuntu 18.04
Free memory > 10 gig. 

Seems like it smth to with the memory. If I use up the memory leaving free only 3 gig, then nothing happens in besu log.
however if I clean up more memory for besu to run it start showing some VMTrace. then just stop the execution returning empty response to "test_importRawBlock".

Correction: besu instance does not crash. 

the expected result is this
```
            "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
                "balance" : "0x0de0b6b3a76586a0",
                "code" : "0x44444243204555",
                "nonce" : "0x00",
                "storage" : {
                    "0x7fe0000000000001" : "0x38335dc6a80d9d82607a3e36ad614d619c0f601ec37fe2facea8e5fd183a4f15"
                }
            },
```

**Comment by shemnon** [comment] 2020-07-22 05:19
That is... unexpected.  What Java version do you have loaded on the box?  `besu --version` should have it in the version string.  One option is to try a different version of Java.  Because the part where it keeps the port open and returns empty is not something I've seen yet.

**Comment by winsvega** [comment] 2020-07-22 10:45
Oh, thanks I will try that for autostop script. 
Besu is the last one remaining with restart issues with auto scripts.

But in this case I start besu manually. Let me check the java. (Btw this happens continually only on this random94 test. Other are fine)

**Comment by winsvega** [comment] 2020-07-22 12:32
```
java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

**Comment by shemnon** [comment] 2020-07-22 17:22
11.0.4 is fairly old.  try 11.0.8 or 14.0.2, or GraalVM 20.1.0

**Comment by winsvega** [comment] 2020-07-22 18:16
Confirm. Using java 14.0.2 fixes the issue.

**Closed** 2020-07-25 10:05 UTC
Labels: P3, bug
