### ISSUE TITLE
Hive failure: withdrawals must not be null when Withdrawals are activated

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#5443] opened 2023-05-08 07:54 UTC
For some reason, there are a lot of hive-failures related to withdrawals. 

https://hivetests.ethdevops.io/viewer.html?suiteid=1683491496-762972274c1239a9d1e3167d512eb306.json&suitename=consensus&testid=3&file=%2Fresults%2Fbesu%2Fclient-9b008ddd0337a0a38b0031d1724689d8d2729b7f7a1921a5f2a164b3bef4a3d5.log#L57

```
2023-05-04 16:02:18.755+00:00 | main | INFO  | BlocksSubCommand | Importing from /blocks/0001.rlp
2023-05-04 16:02:18.910+00:00 | pool-10-thread-1 | WARN  | WithdrawalsValidator$AllowedWithdrawals | withdrawals must not be null when Withdrawals are activated
```
But afaict, the rlp for that test is here: https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/Shanghai/stEIP3651-warmcoinbase/coinbaseWarmAccountCallGas.json#L399 

And the rlp does contain an empty withdrawals-list: 
```
[
  [
    56cc24d2c939d00d7f2855600fe5be55b05bad4661b6198cd6b1d05f0f078988,
    1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
    2adc25665018aa1fe0e6bc666dac8fc2697ff9ba,
    2b29d09b6c7aa1c87d49c20e8812c03ba780eb80a10f718f9ec6a786fc3af801,
    7448d6a08919eafd6a797859e7a67889be5e7cd1f5b6029b836cdd9493f8afd2,
    5aadb4d24dac17099f2c205d796ecf456083d412c0c25dd4078aa1eb55f5c133,
    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
    "",
    01,
    05f5e100,
    a9fb,
    03e8,
    00,
    0000000000000000000000000000000000000000000000000000000000020000,
    0000000000000000,
    0a,
    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
  ],
  [
    [
      01,
      0a,
      013880,
      cccccccccccccccccccccccccccccccccccccccc,
      "",
      693c61390000000000000000000000000000000000000000000000000000000000000000,
      1c,
      44203e8464c0a90a32a53f89baf180e7b4bd7eace546cdcbbdc43e97f637d5df,
      22d3fa42cf3836232cd0044f129419d9d4496bdddc94c25eac0661967e16fac6,
    ],
  ],
  [],
  [],
]

```
PTAL

**Comment by non-fungible-nelson** [comment] 2023-05-08 21:41
Likely addressing root cause in #5442 - we will double check after and make sure.

**Comment by gfukushima** [comment] 2023-05-09 07:16
@holiman I can confirm the test passes when I run it locally. Didn't run all the consensus suite test, only the one you mentioned to ensure that we can now import that block (and all blocks containing withdrawals).

**Comment by gfukushima** [comment] 2023-05-23 02:19
Confirmed that this issue has been fixed and last run of the consensus suite is looking better although still 7000+ failures.
15/05/2023, 20:47:36	consensus	besu	✕ Fail (7470 / 89074)
There's an epic to handle the hive failures so I'm closing this issue that was related to the rlp of blocks with withdrawals.

**Closed by gfukushima** 2023-05-23 02:19 UTC
Labels: TeamGroot
