### ISSUE TITLE
ibft: Invalid block header: timestamp 1619660141 is only 3 seconds newer than parent timestamp 1619660138. Minimum 4 seconds

### ISSUE THREAD

**Issue by helderjnpinto** [hyperledger/besu#2777] opened 2021-09-17 10:25 UTC
Hi, i need some help to find a issue. so to summarize i had a client IBFT with custom hardfork the blockchain as been work with version 1.4 for quite some time and recently i upgraded to version 21.1.3 of besu. 
All works fine but recently i started a new node and importing the current blockchain. By problem here is this:

`11:35:41.821+00:00 | EthScheduler-Workers-3 | INFO | TimestampMoreRecentThanParent | Invalid block header: timestamp 1619660141 is only 3 seconds newer than parent timestamp 1619660138. Minimum 4 seconds
2021-09-16 11:35:41.821+00:00 | EthScheduler-Workers-3 | DEBUG | GetBlockFromPeerTask | Downloading block 0xadbe5ff60e90a91ddb4d5e7d3864954eb7eb54b6a04fe0e5d93e2567dde0a6a6 from peer 0x5e4dcaa4d15b2b386b....
2021-09-16 11:35:41.821+00:00 | EthScheduler-Workers-3 | DEBUG | GetHeadersFromPeerByHashTask | Requesting 1 headers from peer 0x5e4dcaa4d15b2b386b....`

The network mined a block in 3 seconds now i cannot sync from 0 block.
"Invalid block header: timestamp 1619660141 is only 3 seconds newer than parent timestamp 1619660138. Minimum 4 seconds"

In debug mode the validation is hit here: 
![image](https://user-images.githubusercontent.com/12281088/133765393-269ce0c0-531f-4fb3-b29d-20b3920fb737.png)

### Description
As a developer i need to know how i can solve this, what any tools we have to fix this issue.

### Acceptance Criteria
Blocks need to be mined with 4s and not 3s

### Versions (Add all that apply)
* Software version: [`besu --version`]
21.1.3
* Java version: [`java -version`] 
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 13 Linux amd64-64-Bit Compressed References 20200117_151 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 9c5a41bd5f based on jdk-13.0.2+8)

* OS Name & Version: [`cat /etc/*release`]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Additional Information

block: 1419661

hash: 0xadbe5ff60e90a91ddb4d5e7d3864954eb7eb54b6a04fe0e5d93e2567dde0a6a6

timestamp: 1619660141

{

"jsonrpc": "2.0",

"id": 1,

"result": {

"number": "0x15a98d",

"hash": "0xadbe5ff60e90a91ddb4d5e7d3864954eb7eb54b6a04fe0e5d93e2567dde0a6a6",

"mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",

"parentHash": "0xd5a4f1a6953283b9c8dd1f4e1f6eca7109b5a1b64332af6213feebc9b5b45c4b",

"nonce": "0x0000000000000000",

"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",

"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",

"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",

"stateRoot": "0xb721553f8f0bd31881a223405ff24037bbbf851dd6362fbc37ef96a40f8a51ea",

"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",

"miner": "0x3a6c955f61a3b44306591c64cd222d227af0d8d2",

"difficulty": "0x1",

"totalDifficulty": "0x15a98e",

"extraData": "0xf90148a00000000000000000000000000000000000000000000000000000000000000000f854943a6c955f61a3b44306591c64cd222d227af0d8d294b27882d2f4f881863af1e747a240fec26a7bda7c94e2e3868c7232446eca668d9249c90f4e4135234c94f2084fcf38580f43433f15189095f6957ebd5d51808400000000f8c9b8418995e7dd96d1080428970257c412ba26b30ae5faf9a059a9482b2f538c346d4e2cb10b9ba02605f9990da2409db5e28ae508d7318d023bdd90bc21deace5f81500b8412d44479745b11b19fa5c54bdc678586e24f40304cb6df69ca843532fa282f4fd39781d5a3546f19173fee2bee674f6c5bc861ff66f8368b3dc9ffde6558ada2d00b8413b03c1a2adf94515ba2d5aff53ec41c752e7505f507ff797ddcfb8e3d6e5edb5768d2b2c4eadfe75595deff8df31f78e2f41bdf3dc0c62bdc193fac22294d0a101",

"size": "0x34c",

"gasLimit": "0x989680",

"gasUsed": "0x0",

"timestamp": "0x608a0d6d",

"uncles": \[\],

"transactions": \[\]

}

}

parent block: 1419660

hash: 0xd5a4f1a6953283b9c8dd1f4e1f6eca7109b5a1b64332af6213feebc9b5b45c4b

timestamp: 1619660138

{

"jsonrpc": "2.0",

"id": 1,

"result": {

"number": "0x15a98c",

"hash": "0xd5a4f1a6953283b9c8dd1f4e1f6eca7109b5a1b64332af6213feebc9b5b45c4b",

"mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",

"parentHash": "0x5f6b3cc63fb43b29f77b5af462e605b1a399ea91a90222122eff6df52b9d0774",

"nonce": "0x0000000000000000",

"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",

"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",

"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",

"stateRoot": "0xb721553f8f0bd31881a223405ff24037bbbf851dd6362fbc37ef96a40f8a51ea",

"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",

"miner": "0xf2084fcf38580f43433f15189095f6957ebd5d51",

"difficulty": "0x1",

"totalDifficulty": "0x15a98d",

"extraData": "0xf90148a00000000000000000000000000000000000000000000000000000000000000000f854943a6c955f61a3b44306591c64cd222d227af0d8d294b27882d2f4f881863af1e747a240fec26a7bda7c94e2e3868c7232446eca668d9249c90f4e4135234c94f2084fcf38580f43433f15189095f6957ebd5d51808400000001f8c9b8414ca41882a32213b7ccf62a6a5d95ef048e21a799e3278bddae7688ac3728762d6dd374377e27164dbe9fd41e4edab7aef5b8980f4903f82634c8bd57235dfdb700b8410a3bd5ce69aad22b6f70aae33fa97e4c6015a1717672fe50fcecef8d8f02e14d29e49910133bf48d2ae5ee4bf74db182004e1d0f71628ddf91b5fae7da21097000b841fc0c35a43f649e364f1c3ae8ac9825e54128f38c8464c7052b3ff8e18f18db815a9ab965cbd087b34eebbe20c8355a1a2720b2f086381933e9a3f8daf487347b01",

"size": "0x34c",

"gasLimit": "0x989680",

"gasUsed": "0x0",

"timestamp": "0x608a0d6a",

"uncles": \[\],

"transactions": \[\]

}

}

**Comment by macfarla** [comment] 2021-09-20 01:15
The `Minimum 4 seconds` value comes from the blockperiodseconds value in the genesis. Recommend modifying this value to suit your environment.  https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/#genesis-file

**Comment by helderjnpinto** [comment] 2021-09-20 09:18
> The `Minimum 4 seconds` value comes from the blockperiodseconds value in the genesis. Recommend modifying this value to suit your environment. https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/#genesis-file

@macfarla @bgravenorst The suggestion is to put genesis with 3 seconds ??? i don't want that

**Comment by vmichalik** [comment] 2021-09-20 10:29
Hi Helder, The issue arises because your genesis file includes a rule for validating blocks - that they must have a blocktime of minimum 4 seconds, but the chain you are importing has blocks with only 3 seconds between them. 
You can't increase blocktime, since this renders previous blocks invalid. Let us know if this is unclear to you from the documentation or if you expect a different result! If not, I'll go ahead and close this ticket.

**Comment by helderjnpinto** [comment] 2021-09-20 11:07
> Hi Helder, The issue arises because your genesis file includes a rule for validating blocks - that they must have a blocktime of minimum 4 seconds, but the chain you are importing has blocks with only 3 seconds between them.
> You can't increase blocktime, since this renders previous blocks invalid. Let us know if this is unclear to you from the documentation or if you expect a different result! If not, I'll go ahead and close this ticket.

@vmichalik I know that i can't change the genesis but how i fix this issue?
And i notice the old client don't have this rules for header validation. 
(old client)
![image](https://user-images.githubusercontent.com/12281088/133992469-29f8d71c-2110-4d9b-bc22-996b31da14f2.png)


So my genesis file is the same as other older blocks nothing change only my upgrade of besu from 1.40 to 21.1.3. With the older version i can import the blockchain but with the new i can't. 

Why is the reason for create one block in less than 3 seconds and other validators accepted?? exist any issue with difference in timestamps ?

And how i resolve this problem?

**Comment by jframe** [comment] 2021-09-21 05:24
Hi @helderjnpinto, 
I've been able to reproduce the issue locally and am working on a fix for it.

We have always had this header validation in IBFT. What's interesting is that even though blocks are created with a time difference of less than the block period they aren't rejected as being invalid at the time they are created.

**Comment by helderjnpinto** [comment] 2021-09-21 11:30
Ok cool @jframe. I will wait for news thanks.

**Comment by vmichalik** [comment] 2021-09-27 07:46
Hey @helderjnpinto, we have a potential solution we are testing and hope to push for your review in the latter half of next week

**Comment by helderjnpinto** [comment] 2021-09-30 08:58
> Hey @helderjnpinto, we have a potential solution we are testing and hope to push for your review in the latter half of next week

Sure i will test when it's here. Thanks!

**Comment by jframe** [comment] 2021-10-08 07:47
hey @helderjnpinto,

We have worked out what the underlying issues were. Blocks can on occasion be created too early due to the timer returning too early in some cases. This is largely mitigated in the latest version of Besu by how we determine the block header timestamp.

There is also a bug in the version of Besu you are using which causes the IBFT2 header validation for the block period to not validate the block timestamp correctly which is why those blocks are being allowed to be added to the chain. This bug is not present in the latest version of Besu.

The solution to fix this and allow for upgrading to the new version with an IBFT2 chain that has incorrect block header timestamps is to
- Decrease the existing block period in the IBFT2 config to a lower value that satisfies the block header validation. In your case that would be to reduce the block period to 3s.
- Allow for changing the block period using a transition #2797 so the original block period can be used for new blocks.

Once #2797 is complete it will be possible for you to upgrade your IBFT2 chain to the latest version of Besu.

**Comment by jframe** [comment] 2021-11-01 07:58
The feature for changing the block period will be included in the Besu 21.10.1 release.

**Closed by jframe** 2021-11-01 07:58 UTC
Labels: bug, TeamGroot, P2, consensus
