### ISSUE TITLE
RPC connectivity issue

### ISSUE THREAD

**Issue by blockchain-app12** [hyperledger/besu#3348] opened 2022-01-29 05:52 UTC
I running the besu node setup in private chain. Totally 4 nodes.
1 node is master node and others are peer nodes.
Then none of the RPC method was not working while we trying to get response.
Kindly let me know the solution for the issue to resolve this.

![image](https://user-images.githubusercontent.com/48212011/151649352-a49c8fa4-733f-4594-82a4-cd8584149104.png)

**Comment by macfarla** [comment] 2022-02-03 03:49
👋  @osiz-blockchainapp - can you tell us a bit more about your besu setup - can you share your besu config file as well as version info:

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by osiz-blockchainapp** [comment] 2022-02-04 11:36
> wave @osiz-blockchainapp - can you tell us a bit more about your besu setup - can you share your besu config file as well as version info:
> ### Versions (Add all that apply)
> 
>     * Software version: [`besu --version`]
> 
>     * Java version: [`java -version`]
> 
>     * OS Name & Version: [`cat /etc/*release`]
> 
>     * Kernel Version: [`uname -a`]
> 
>     * Virtual Machine software & version: [`vmware -v`]
> 
>     * Docker Version: [`docker version`]
> 
>     * Cloud VM, type, size: [Amazon Web Services I3-large]

Hi,
Followed this link: https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

Versions:
Besu: besu/v21.1.4/linux-x86_64/openjdk-java-11
Java: openjdk version "11.0.13"
OS & Version: Ubuntu & 20.04.3 LTS (Focal Fossa)
Kernal version:  5.11.0-1020-aws #21~20.04.2-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux
VM: No
Docker: No
Cloud Vm, type, size: AWS, 150GB

**Comment by macfarla** [comment] 2022-02-07 23:18
Since you're trying to access a machine on AWS, I'm guessing the issue is in allowing that request in and out. By default, Besu accepts traffic from localhost/127.0.0.1 only. https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#host-allowlist
* can you set host-allowlist=["*"] and retry
* if that works, then change ["*"] to the list of client IPs that you want to allow
* if you still get the same error, can you verify that executing the curl request _from the same host_ can work ie accessing via localhost

**Comment by macfarla** [comment] 2022-02-17 00:06
Hi @osiz-blockchainapp - are you still having issues with this?

**Comment by MadelineMurray** [comment] 2022-02-22 00:13
hi @osiz-blockchainapp - we're closing this one.  If you're having issues in the future, please reopen.

**Closed by MadelineMurray** 2022-02-22 00:13 UTC
Labels: dev experience
