### ISSUE TITLE
Check if the capability is shared before making requests

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#6420] opened 2024-01-17 07:45 UTC
### Description
Currently we do not check whether an EthPeer supports the request that we are sending, e.g. when we are sending a GetStorageRangeFromPeerTask to a peer we should check whether that peer has the capability to do SNAP.
We need to think about at what point this should be checked. It should be done when we are selecting the peers for the retrying tasks, but we might need to do that as well for the simple tasks (e.g. GetStorageRangeFromPeerTask).

**Comment by macfarla** [comment] 2024-04-24 01:57
current PR https://github.com/hyperledger/besu/pull/6609

**Comment by macfarla** [comment] 2024-04-24 01:58
closing as duplicate of #6349

**Closed by macfarla** 2024-04-24 01:58 UTC
Labels: TeamRevenant, peering
