### ISSUE TITLE
Make database corruption issue more explicit in Besu logs at startup

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#546] opened 2020-03-22 02:25 UTC
One of our customer faced issues when a database corruption happened. Having more details (logs?) when Besu can't start because of a corrupted database and how to recover (if possible) would be great.

Originally raised by @NicolasMassart

**Comment by RatanRSur** [comment] 2021-05-19 15:17
@NicolasMassart do we know what the user ended up seeing? Some types of corruption aren't detectable at start-time. Only when the data is missing. Closing for now unless you have more info.

**Closed by RatanRSur** 2021-05-19 15:17 UTC

**Comment by NicolasMassart** [comment] 2021-05-19 19:12
I don't have the ticket history for this as it's too old and we made some migration in Zendesk since.
But basically it was just displaying a stack trace instead of a clear message as "Your Besu database is corrupted and Besu can't start. Please repair [link to some tutorial to repair]" or alike.

**Comment by RatanRSur** [comment] 2021-05-19 19:34
Given the age, I wouldn't be surprised if this was pruning related and has since been fixed. We haven't seen those corruptions in a long while.

**Comment by NicolasMassart** [comment] 2021-05-19 19:53
For what I recal it was corrupted due to a disk space saturation so the DB was not able to save logs form memory. It was very hard to reproduce as it requires some very bad luck...
