### ISSUE TITLE
Basu does not respond to Teku

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#4221] opened 2022-08-04 22:32 UTC
I was running Besu, and it was synced 
When I connected Teku with --ee-endpoint=http://localhost:8551 it reported EE Failure: 

```
2022-08-04 01:47:59.478+03:00 | CompletableFutureDelayScheduler | ERROR | teku-event-log | [31mExecution Client is offline[0m
java.util.concurrent.TimeoutException: null
2022-08-04 01:47:59.504+03:00 | beaconchain-async-5 | ERROR | MergeTransitionConfigCheck | An error occurred while querying remote transition configuration
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid remote response: TimeoutException
2022-08-04 01:51:12.912+03:00 | pool-3-thread-5 | WARN  | FallbackAwareEth1Provider | Retrying with next eth1 endpoint

```

Later on Teku reported that 
`2022-08-04 01:53:58.530+03:00 | pool-3-thread-4 | INFO  | teku-event-log | [32mExecution Client is back online[0m`

Then it reported that "Execution Client is offline" again, and then again reported that "Execution Client is back online" and so on few times 

From Besu  log I can see the following: 
[besu.besu-22.7.0.1.log](https://github.com/hyperledger/besu/files/9263785/besu.besu-22.7.0.1.log)

```
2022-08-04 01:46:15.303+03:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
2022-08-04 01:51:12.912+03:00 | vert.x-worker-thread-1 | WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - getBlockBody ], aborting process.
2022-08-04 01:51:28.165+03:00 | vert.x-worker-thread-5 | WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - getBlockBody ], aborting process.
2022-08-04 01:52:37.784+03:00 | vert.x-worker-thread-12 | WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process.
2022-08-04 01:53:02.304+03:00 | vert.x-worker-thread-2 | WARN  | BackendQuery | Zombie backend query detected [ matchingLogs - blockIsOnCanonicalChain ], aborting process.
2022-08-04 02:00:58.515+03:00 | vert.x-eventloop-thread-4 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected


```

Start args: 

```
%JAVA_HOME%/bin/java -cp besu-22.7.0/lib/* org.hyperledger.besu.Besu ^
   --sync-mode=X_SNAP --data-storage-format=BONSAI --rpc-http-enabled ^
    --network=goerli --data-path C:/eth2D/goerli  >> besu.besu-22.7.0.log 2>&1

```

* Software version: besu-22.7.0
* Teku: v22.8.0
* Java version: openjdk-18.0.1.1
* OS Name & Version: Windows 11 Pro 22H2  22621.232
* Kernel Version: 22621.232
* System info - 16Gb, Intel(R) Core(TM) i5-9600K CPU, 1TB Samsung Evo Plus EVME

**Comment by daniellehrner** [comment] 2022-08-05 11:09
The port 8551 is secured with a JWT token, but it seem you have not set it. 

How to create it and set it, is described here: https://besu.hyperledger.org/en/stable/Tutorials/Merge-Testnet/#2-generate-the-shared-secret

**Comment by jwhelan72** [comment] 2022-08-06 22:51
I have the same error appearing and I have set the JWT token correctly.  Besu keeps dropping and then coming back online.

Note: only seems to happen when Teku is running, so something is clashing between them it appears.

**Comment by daniellehrner** [comment] 2022-08-08 10:52
It seems this has to be answered on Discord by the Teku team: https://discord.com/channels/905194001349627914/938504958909747250/1005657962423013487

**Comment by non-fungible-nelson** [comment] 2022-08-08 16:36
Closing for Teku resolution in the Discord

**Comment by ajsutton** [comment] 2022-08-08 23:28
I would still argue that besu should be able to handle requests for log events across a wide range of blocks without timing out. This used to work and seems to have regressed.

**Comment by ajsutton** [comment] 2022-08-08 23:31
Going to reopen this so it doesn't get lost. There's some performance regression going on here.

**Comment by ibhagwan** [comment] 2022-08-09 12:27
Quick question, I just upgraded to Besu v22.7.0 used with nimbus-eth2 v22.7.0 (same version number, not sure if intentional?).

In prepration for the merge I wanted to test my jwt secret configuration so I used the new flag `--engine-rpc-enabled` (#4190), made sure the port was open with `netstat -tulpn | grep 8551` and configured nimbus with both `--web3-url=http://localhost:8551` and `--jwt-secret=...`.

On the nimbus side I don't see any warnings and attestations are working as expected, however, on the Besu side I keep getting the warning implemented by #3569 every 2 minutes:
```
vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration |
  not called in 120 seconds, consensus client may not be connected
```

- Given the merge is still away on mainnet, Is this intentional and I can ignore this message safely?
- Wil my next block proposal work or would you recommend running the non-authenticatd endpoint (port 8545) until TTD is announced and nimbus releases an update?

**Comment by kirillp** [comment] 2022-08-09 15:31
@ibhagwan it is not related to the issue, you have missed something in your config, here is my working config:

`set pass=--engine-jwt-secret=C:/eth2D/goerli/jwt.secret.hex 
set rpc=--rpc-http-enabled

%JAVA_HOME%/bin/java -cp besu-22.7.0/lib/* org.hyperledger.besu.Besu --network=goerli ^
 --data-path C:/eth2D/goerl_chk --sync-mode=X_SNAP --data-storage-format=BONSAI  ^
  %pass% %rpc%  >> besu.besu-22.7.0.log 2>&1
`

`title "teku testnet"

set infuraState=.....@eth2-beacon-prater.infura.io/eth/v2/debug/beacon/states/finalized

set fee=0xA...

set ee_ip=http://localhost:8551
set password="goerli\jwt.secret.hex"

teku-22.8.0/bin/teku.bat --network=prater --data-path goerli --initial-state=%infuraState% ^
 --ee-endpoint=%ee_ip% --ee-jwt-secret-file %password% ^
 --validators-proposer-default-fee-recipient=%fee% ^
 --validator-keys test_validator.json;test_validator.dat
`

**Comment by ajsutton** [comment] 2022-08-09 23:46
@ibhagwan Since the merge isn't scheduled for Mainnet yet, it's likely Nimbus isn't making calls to the transitionConfiguration API yet because it doesn't expect the EL to have the configuration set. So those warnings are expected until you update Nimbus to a version which has the merge configuration included for Mainnet (that config hasn't yet been decided). If Nimbus was trying and failing to connect I'd expect you'd see errors in the Nimbus logs.

**Comment by ibhagwan** [comment] 2022-08-09 23:48
Ty @ajsutton!

**Comment by ajsutton** [comment] 2022-08-10 04:29
For the record, I'm seeing this when Teku restarts even after it has sync'd all the deposit logs. So it's not caused by single queries over a large number of blocks for deposit event logs. During startup Teku does have to fill it's cache of eth1 blocks it may need to vote on so sends quite a few `eth_getBlockByNumber` requests and these seem to be enough to cause besu to not respond.

**Comment by ajsutton** [comment] 2022-08-11 23:40
Ok, I think besu has been incorrectly blamed for this one - it is slow responding to eth_getLogs requests and it may be worth optimising that but there are two factors which are causing this to suddenly show up so often and persistently, both issues in Teku:

 1. When switching from `eth1-endpoint` to `ee-endpoint` there are tighter timeouts applied (8 seconds maximum for a request which is from the execution engine API spec).
 2. Those tighter timeouts surface out of the HTTP client Teku uses slightly differently so we _weren't_ reducing the block rage of eth_getLogs events and so would repeatedly hit the timeout for the same request.

Both issues are fixed with https://github.com/ConsenSys/teku/pull/6061 so I'm going to close this one. Optimising eth_getLogs is much less of a priority and can just be handled as part of normal optimising efforts, it doesn't appear to be significantly worse than it was in the past.

**Closed by ajsutton** 2022-08-11 23:40 UTC
Labels: TeamChupa
