### ISSUE TITLE
Also impossible to start and sync after upgrading to 21.10.1

### ISSUE THREAD

**Issue by emclab** [hyperledger/besu#3056] opened 2021-11-13 01:50 UTC
### Description
As an [Actor], I want [feature] so that [why]. 
Just a routine upgrade to 21.10.1 but it seems taking forever to start and sync. Here is the log on boot node

```
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8Setting logging level to DEBUG
2021-11-13 09:33:18.651+08:00 | main | DEBUG | Native | Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487 for /com/sun/jna/linux-x86-64/libjnidispatch.so
2021-11-13 09:33:18.655+08:00 | main | DEBUG | Native | Found library resource at jar:file:/home/besu/lib/jna-5.8.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
2021-11-13 09:33:18.656+08:00 | main | DEBUG | Native | Extracting library to /root/.cache/JNA/temp/jna15952452044082990503.tmp
2021-11-13 09:33:18.658+08:00 | main | DEBUG | Native | Trying /root/.cache/JNA/temp/jna15952452044082990503.tmp
2021-11-13 09:33:18.660+08:00 | main | DEBUG | Native | Found jnidispatch at /root/.cache/JNA/temp/jna15952452044082990503.tmp
2021-11-13 09:33:18.708+08:00 | main | DEBUG | NativeLibrary | Looking for library 'secp256k1'
2021-11-13 09:33:18.710+08:00 | main | DEBUG | NativeLibrary | Adding paths from jna.library.path: null
2021-11-13 09:33:18.710+08:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2021-11-13 09:33:18.711+08:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
2021-11-13 09:33:18.714+08:00 | main | DEBUG | NativeLibrary | Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /usr/lib64, /lib64, /usr/lib, /lib, /usr/lib/x86_64-linux-gnu/libfakeroot]
2021-11-13 09:33:18.715+08:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2021-11-13 09:33:18.715+08:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
2021-11-13 09:33:18.715+08:00 | main | DEBUG | NativeLibrary | Looking for version variants
2021-11-13 09:33:18.722+08:00 | main | DEBUG | Native | Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487 for secp256k1
2021-11-13 09:33:18.722+08:00 | main | DEBUG | Native | Found library resource at jar:file:/home/besu/lib/secp256k1-0.4.2.jar!/linux-x86-64/libsecp256k1.so
2021-11-13 09:33:18.726+08:00 | main | DEBUG | Native | Extracting library to /root/.cache/JNA/temp/jna16572857017669824082.tmp
2021-11-13 09:33:18.732+08:00 | main | DEBUG | NativeLibrary | Found library 'secp256k1' at /root/.cache/JNA/temp/jna16572857017669824082.tmp
```

From the log above, the time stopped at 10min before and no more log produced. Tried reboot the server and systemctl start/restart boot node.service. Also tried to download from besu website a few times and unzip with tar 3 times.

Some release start and sync very quickly but not 21.10.1. Besu has shown difficulty to start and sync with previous releases quite often.

### Acceptance Criteria
* [Criteria 1]
* Shall be start and sync shortly

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
Taking forever to start and sync. 
**Frequency:** [What percentage of the time does it occur?]
After upgrading to 21.10.1 today
### Versions (Add all that apply)
* Software version: [`besu --version`]:21.10.1
* Java version: [`java -version`] 
* openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
* OS Name & Version: [`cat /etc/*release`] ubuntu 20.04
* Kernel Version: [`uname -a`]
* Linux iZbp12yua3rgr6qd3cj455Z 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by MadelineMurray** [comment] 2021-11-15 01:08
Thanks for raising @emclab - we'll investigate in our current sprint. 

First steps - try and reproduce.  How often this occurs will decide the severity level.

**Comment by taccatisid** [comment] 2021-11-15 22:10
On my machine the next step (that we don't see here due to a lack of progress) would be
```
2021-11-16 11:05:25.907+13:00 | main | DEBUG | NativeLibrary | Looking for library 'eth_pairings'
```

**Comment by taccatisid** [comment] 2021-11-16 01:22
@emclab could you try the new version 21.10.2 to see whether the issue remains?

**Comment by sajz** [comment] 2021-11-23 16:49
@emclab did this solve your problem?

**Comment by macfarla** [comment] 2021-11-30 23:05
this might also be related to entropy - see https://github.com/hyperledger/besu/issues/1464

**Comment by emclab** [comment] 2021-12-21 01:49
sorry for late reply. I have upgraded to 21.10.4 and I have hard time to get 4 nodes up today on server. Node4 is refusing to be started.

**Comment by macfarla** [comment] 2021-12-21 04:19
Hi @emclab that sounds like a different issue - could you open a new github issue and provide logs, code and OS versions etc as per the issue template? Thanks!

**Comment by macfarla** [comment] 2021-12-21 04:20
Also - would recommend 21.10.5 - it is the same as 21.10.4 but with log4j updated (again)

**Comment by macfarla** [comment] 2022-01-05 20:19
Hi @emclab - I'm going to close this issue but do open a new one if you're still having problems

**Closed by macfarla** 2022-01-05 20:19 UTC
