### ISSUE TITLE
Reject on high timestamp difference for blocks - why and why isn't it consistent

### ISSUE THREAD

**Issue by qbzzt** [hyperledger/besu#2546] opened 2021-07-17 17:19 UTC
### Description

When I run a test case with a large difference in timestamps between two consecutive blocks, I get this error in the log:
```
2021-07-17 17:06:42.628+00:00 | vert.x-worker-thread-19 | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 20000010000 is greater than the timestamp margin 1626541617
```

And the block is rejected with this RPC reply:
```
{
  "jsonrpc" : "2.0",
  "id" : 13,
  "error" : {
    "code" : -32000,
    "message" : "Could not import Block"
  }
}
```

This seems weird, for two reasons:

1. I can't find in the Yellow Paper any criteria for the block timestamp except for inequality (49) on page 7 (see https://ethereum.github.io/yellowpaper/paper.pdf). So if we ever had a lull of about thirty minutes during which no blocks were created, it would break consensus.

2. Even if there is such a limit, shouldn't it be consistent? I ran the same test twice with a minute between them, and the limit seems to grow by one microsecond every second (see the first and last lines):

```
2021-07-17 17:15:27.477+00:00 | vert.x-worker-thread-5 | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 20000010000 is greater than the timestamp margin 1626542142
2021-07-17 17:16:29.222+00:00 | vert.x-worker-thread-6 | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [London: 0]
2021-07-17 17:16:29.247+00:00 | vert.x-worker-thread-13 | INFO  | CalculatedDifficultyValidationRule | Invalid block header: difficulty 131072 does not equal expected difficulty 131136
2021-07-17 17:16:29.254+00:00 | vert.x-worker-thread-16 | INFO  | CalculatedDifficultyValidationRule | Invalid block header: difficulty 131072 does not equal expected difficulty 3686656
2021-07-17 17:16:29.257+00:00 | vert.x-worker-thread-17 | INFO  | CalculatedDifficultyValidationRule | Invalid block header: difficulty 131072 does not equal expected difficulty 131136
2021-07-17 17:16:29.260+00:00 | vert.x-worker-thread-18 | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 20000010000 is greater than the timestamp margin 1626542204
```

**Comment by vmichalik** [comment] 2021-07-20 11:20
Hey @qbzzt, thanks for raising an issue! This seems like unexpected behavior to me, we'll investigate further.

**Comment by garyschulte** [comment] 2021-07-26 18:44
Hi @qbzzt - which test(s) are you getting this behavior for?  

It looks like the header validation rule is comparing against the system clock rather than the retesteth clock:
https://github.com/hyperledger/besu/blob/master/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampBoundedByFutureParameter.java#L47-L57

Are you getting this when trying to fill tests or when you are running against existing filled tests?

**Comment by qbzzt** [comment] 2021-07-27 17:08
I get this when using the filled test (see [badTimestamp.json](https://github.com/hyperledger/besu/files/6887432/besu-timestamp.json.txt)) and when filling the test (see [badTimestampFiller.yml](https://github.com/hyperledger/besu/files/6887433/besu-timestamp.yml.txt)).

The timestamp margin changes between different runs:
```
2021-07-27 17:02:12.440+00:00 | vert.x-worker-thread-8 | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 2700000000 is greater than the timestamp margin 1627405347
2021-07-27 17:02:49.092+00:00 | vert.x-worker-thread-9 | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [London: 0]
2021-07-27 17:02:49.115+00:00 | vert.x-worker-thread-12 | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 2700000000 is greater than the timestamp margin 1627405384
```

**Comment by garyschulte** [comment] 2021-08-04 17:45
These failing difficulty test cases were due to block timestamps in the future, well past the blockchain's system clock.  

The PR above used the retesteth clock in the Future Timestamp rule check so that we *could* import future blocks, but the test engine would have to explicitly advance the clock in order for these blocks to successfully import during a test.  This also broke other existing test assumptions.  

After discussion, it was deemed that the difficulty tests could be written with past block times without need for blocks with future timestamps.  I am closing this issue for that reason.  @qbzzt, feel free to re-open if this functionality is necessary.

**Closed by garyschulte** 2021-08-04 17:45 UTC
Labels: P5, bug

**Comment by gooooer** [comment] 2022-06-10 07:03
Hi guys, I'm having this same issue when I spin up my cluster of TX nodes in k8s. I have the first transaction node that is fully synced and I spawned the second node and put reference to first one via static node. The sync of the entire ledger went well. However right after second node caught up with all blocks it fired an error:

```
2022-06-10 06:49:12.787+00:00 | EthScheduler-Services-9 (validateHeadersJoin) | INFO  | TimestampBoundedByFutureParameter | Invalid block header: timestamp 1654843775 is greater than the timestamp margin 1654843753
2022-06-10 06:49:12.788+00:00 | EthScheduler-Services-9 (validateHeadersJoin) | WARN  | PipelineChainDownloader | Invalid block detected. Disconnecting from sync target. Invalid checkpoint headers.  Headers downloaded between #5942477 (0x22cba4047db02efad0dc03b1c13fdc8a6c895dd56ce04155813e4780db25d2a8) and chain head do not connect at #5942478 (0x49098e013eca9e519f47b3ba73e6ab92396952ba5a915710be7a1337e8e55543): Invalid block at #5942478 (0x49098e013eca9e519f47b3ba73e6ab92396952ba5a915710be7a1337e8e55543)
2022-06-10 06:49:12.789+00:00 | EthScheduler-Services-9 (validateHeadersJoin) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Invalid checkpoint headers.  Headers downloaded between #5942477 (0x22cba4047db02efad0dc03b1c13fdc8a6c895dd56ce04155813e4780db25d2a8) and chain head do not connect at #5942478 (0x49098e013eca9e519f47b3ba73e6ab92396952ba5a915710be7a1337e8e55543): Invalid block at #5942478 (0x49098e013eca9e519f47b3ba73e6ab92396952ba5a915710be7a1337e8e55543)
```

I tried to restart the second node, tried to remove static node file and play with different versions of Besu, but issue still persists. 

Any idea how can I fix it?

**Comment by gooooer** [comment] 2022-06-10 16:33
Ok, sorry for messing with this - my issue was is that time didn't sync properly between two k8s nodes. Setting up NTP on both of them to work properly solved the issue.
