### ISSUE TITLE
Support switching PoW algorithms

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#2692] opened 2021-08-30 06:27 UTC
### Description
Support switching PoW algorithms (Keccak vs ethash) at a given block through a RPC method or a configuration.

We want to make it possible for folks to choose a new pow algorithm through RPC. When this pow method is selected, the client can be configured to change its pow algorithm at will, providing the block number is in the future.

**Comment by vmichalik** [comment] 2021-08-31 10:20
it may make sense to reuse some of the same functionality we use in IBFT and QBFT for changing parameters, (called transitions). tagging @jframe to weigh in!

https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Add-Validators/#adding-and-removing-validators-without-voting_1

**Comment by jframe** [comment] 2021-09-12 23:51
Using transitions could be a good way to do this. It was intended to be a general purpose way of providing a custom forking mechanism although right now it is only used for ibft2 and qbft. This is the design doc that outlines what was done https://wiki.hyperledger.org/display/BESU/Switchable+Consensus+Parameters

**Comment by macfarla** [comment] 2024-12-06 03:46
PoW is now deprecated so we won't be adding features to it

**Closed by macfarla** 2024-12-06 03:46 UTC
Labels: enhancement, ETC, mining
