### ISSUE TITLE
Multi-tenancy: Check if user has access to privacy group data can add multiple roundtrips between Besu and Orion

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#1383] opened 2020-09-18 06:24 UTC
### Description
The check if a user has access to a certain privacy group is currently done every time data from that group is accessed. There is a MultiTenancyPrivacyController class that implements the checks. 
When pantheon privacy is used the check includes a call to enclave.retrievePrivacyGroup that retrieves the members of the privacy group, in the case of on-chain privacy checking membership is done with a call to the privacy groups management contract to get the participants of the privacy group. 
One example: Eea_sendRawTransaction will do multiple checks: One check in the class itself. When validating the private transaction, group membership is checked twice, once in the method itself, and once when determining the nonce. 
The greatest number of group memberships checks happen when a new participant is added to an on-chain group and group membership is checked for each private transaction that is added to the data blob that is sent to the new participant.

**Comment by macfarla** [comment] 2021-11-17 04:22
Duplicate of https://github.com/hyperledger/besu/issues/2990

**Closed by macfarla** 2021-11-17 04:22 UTC
Labels: enhancement, privacy, TeamRevenant
