### ISSUE TITLE
failing to start a bootnode

### ISSUE THREAD

**Issue by mwampetaipyana** [hyperledger/besu#4422] opened 2022-09-22 09:30 UTC
[error.txt](https://github.com/hyperledger/besu/files/9624357/error.txt)

  

[error.txt](https://github.com/hyperledger/besu/files/9624730/error.txt)

**Comment by macfarla** [comment] 2022-10-10 05:21
duplicate of #4428 (fixed)

**Closed by macfarla** 2022-10-10 05:21 UTC
