### ISSUE TITLE
Contract deploy always fails when block.chainid calculated inside constructor. (Internal Error)

### ISSUE THREAD

**Issue by ubudragon** [hyperledger/besu#3272] opened 2022-01-13 04:56 UTC
Contract deploy always fails at the stage of eth_estimateGas. 
It happens only with besu network. (hardhat network, geth, rinkeby, binance, etc. - all works just fine)

sample Contract code:
` pragma solidity ^0.8.0; contract BesuTest {
  uint256 cId;
  constructor() {
    cId = block.chainid;
  }
}`

deploy script:
`const contractFactory = await ethers.getContractFactory("BesuTest");
const contractInstance = await contractFactory.deploy();`

Error message:
`ProviderError: Internal error
    at HttpProvider.request 
    at LocalAccountsProvider.request 
    at processTicksAndRejections
    at async EthersProviderWrapper.send`

### Steps to Reproduce (Bug)
1. clone sample repo: https://github.com/GemunIon/besutest
2. install deps: npm i
3. compile contract: hardhat compile
4. start besu: docker-compose up -d 
5. run deploy: hardhat run scripts/deploy.ts --network besu

**Expected behavior:**
The contract should be deployed.

### Versions (Add all that apply)
* Software version: [`besu/v22.1.0-RC2/linux-x86_64/openjdk-java-11`]
* Java version: [`"16.0.2"`]
* OS Name & Version: [`MacOS 10.15.7 `]
* Docker Version: [`20.10.10`]

Genesis file:
{
  "config": {
    "chainId": 1337,
    "petersburgBlock": 0,
    "contractSizeLimit": 2147483647,
    "ethash": {
      "fixeddifficulty": 100
    }
  },
  "nonce": "0x42",
  "timestamp": "0x0",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x1fffffffffffff",
  "difficulty": "0x10000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {..besu wallets..}
}

### Additional Information
sample repo: https://github.com/GemunIon/besutest

**Comment by frankisawesome** [comment] 2022-01-17 07:09
hey @ubudragon the exception you've attached is on the hardhat side which I'm not too familiar with, I can replicate the exception however I can't see anything that's gone wrong on the Besu side -> right before the internal error was thrown Besu returns a 200 on a eth_estimateGas call. Let me know your thoughts.

**Comment by MadelineMurray** [comment] 2022-02-08 00:31
hi @ubudragon - it looks like is not a bug on the Besu side so closing this one.  If you have more questions, could you re-open or create another issue please.

**Closed by MadelineMurray** 2022-02-08 00:31 UTC
Labels: bug, P3, TeamRevenant

**Comment by PavelZavadskiy** [comment] 2022-02-14 08:39
I have a similar issue.
https://github.com/hyperledger/besu/issues/3417

**Comment by TrejGun** [comment] 2022-03-05 12:58
this could be fixed by setting `"muirglacierblock": 0,` in your genesis file

https://besu.hyperledger.org/en/stable/HowTo/Configure/Genesis-File/
