### ISSUE TITLE
Memory leak when interacting with a smart contract resulting in node crashing

### ISSUE THREAD

**Issue by calmacfadden** [hyperledger/besu#5006] opened 2023-01-26 14:08 UTC
### Description
Besu 22.4.3 
When performing a certain smart contract function call the node eventually crashes due to what seems like a memory leak. 
The this error keeps looping .
 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-7,5,main] has been blocked for 63767 ms, time limit is 60000 ms

eventually the node gives the error "java.lang.OutOfMemoryError: Java heap space"

The transaction is not even submitted. This happens when the node simulates the transaction. 

### Exception (Thread Block)

Jan 26 12:32:04 ip-10-203-1-28 besu[575717]: 2023-01-26 12:32:04.790+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-7,5,main] has been blocked for 63767 ms, time limit is 60000 ms
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]: io.vertx.core.VertxException: Thread blocked
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at java.base@11.0.17/java.util.TreeMap.getEntry(TreeMap.java:357)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at java.base@11.0.17/java.util.TreeMap.get(TreeMap.java:277)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:203)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.gascalculator.BerlinGasCalculator.calculateStorageCost(BerlinGasCalculator.java:165)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.operation.SStoreOperation.execute(SStoreOperation.java:64)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.EVM.lambda$executeNextOperation$0(EVM.java:87)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.EVM$$Lambda$1415/0x0000000840728c40.execute(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.tracing.EstimateGasOperationTracer.traceExecution(EstimateGasOperationTracer.java:30)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.EVM.executeNextOperation(EVM.java:81)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:74)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:485)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:397)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:146)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.transaction.TransactionSimulator.processWithWorldUpdater(TransactionSimulator.java:217)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:160)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:108)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthEstimateGas.response(EthEstimateGas.java:81)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:42)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:91)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$6(JsonRpcExecutorHandler.java:76)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler$$Lambda$723/0x000000084052bc40.handle(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1126/0x00000008406a2c40.handle(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.ContextImpl$$Lambda$1129/0x00000008406a4040.handle(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.ContextImpl$$Lambda$1128/0x00000008406a3840.run(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.vertx.core.impl.TaskQueue$$Lambda$294/0x0000000840410440.run(Unknown Source)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jan 26 12:32:04 ip-10-203-1-28 besu[575717]:         at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)

**Comment by non-fungible-nelson** [comment] 2023-01-26 15:02
Can you provide the exact RPC call you are using? Might be related to the work that @daniellehrner is doing to fix some RPC calls.

**Comment by daniellehrner** [comment] 2023-01-27 09:54
This error is not related to the OOM while tracing a block. This issue occurs while calling [eth_estimateGas](https://besu.hyperledger.org/en/stable/public-networks/reference/api/#eth_estimategas).

@calmacfadden Could you provide more details what type of transaction you are sending? From the log output I can see that it seems to be stuck somewhere. But I cannot say what is causing it.

**Comment by calmacfadden** [comment] 2023-01-27 12:32
I have not been able to re-create the issue on a fresh contract, but I have a buggy contract which was broken during a proxy upgrade. 

The contract was deployed which has a function referencing a struct. The struct contained a bytes32 which was never used directly used but lots of the Mydata structs were added to different mappings in the contract.
The bytes32 data field was accidentally removed from the struct during an upgrade. 

```
struct Mydata {
   uint256 value,
   string name,
   bytes32 data 
}
```

This was upgraded to: 

```
struct Mydata {
   uint256 value,
   string name 
}
```

Putting the bytes32 value back into the struct and upgrading the contract again seems to have fixed the issue, but in reality the contract shouldn't be crashing the node when something is wrong with the contract. 

Some more information:
The max gas for the transaction and block are set to the max possible value. So possibly the contract is caught in some loop and consumes all the memory on the server?

**Comment by ahamlat** [comment] 2023-01-30 14:17
@calmacfadden Did you specify -Xmx Java option to your Besu node ? Otherwise, what is the RAM size on the machine you 're doing your tests ?
I don't know if is possible de share the whole process to reproduce, then I can generate a heap dump and analyse it. We'll need the buggy contract and the called function.
The thread is blocked on getting storage values from disk on SSTORE operation

**Comment by calmacfadden** [comment] 2023-01-30 17:23
No im not using -Xmx

Ill try and recreate it again as i currently fixed the contract.

**Comment by ahamlat** [comment] 2023-02-22 12:31
As we cannot reproduce from our side, I suggest to close this issue and reopen it if you notice the issue again with the fixed version of your contract.

**Closed** 2023-03-02 19:39 UTC
Labels: bug, RPC
