### ISSUE TITLE
Error message when output directory already exists isn't clear

### ISSUE THREAD

**Issue by blockchain-trainer** [hyperledger/besu#643] opened 2020-03-18 07:25 UTC
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

indicates that it does.

IBFT-Network/
├── Node-1
│   ├── data
├── Node-2
│   ├── data
├── Node-3
│   ├── data
└── Node-4
    ├── data

Copy the following configuration file definition to a file called ibftConfigFile.json and save it in the IBFT-Network directory:

**Comment by MadelineMurray** [comment] 2020-04-03 03:49
@blockchain-trainer - I've transferred this over to the `besu` repository to reflect it's a code change rather than a docs change.  
 
I think Grant's suggestion of `Output directory already exists` would make it clearer what the issue is in this case.

**Comment by blockchain-trainer** [comment] 2020-04-04 09:41
submitted [PR](https://github.com/hyperledger/besu/pull/652)

**Closed** 2020-04-20 02:44 UTC
Labels: good first issue
