### ISSUE TITLE
[Investigation] Besu can still lose many peers during sync 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4617] opened 2022-11-07 15:45 UTC
### Description
As a user, I want to keep my peers to ensure I can sync and stay at chain head. Potentially because threads were blocked, we lost many peers 
Vertx for example uses different approaches to threading  

### Acceptance Criteria
* More stable peer numbers 

### Timebox
* Investigating the root cause: 2 days

**Comment by macfarla** [comment] 2023-01-13 01:56
anecdotal evidence that this is better in 23.1.0-RC1

**Comment by iamhsk** [comment] 2023-02-03 02:40
Closing this one. Potential duplicate of #4616

**Closed by iamhsk** 2023-02-03 02:40 UTC
Labels: TeamRevenant, peering
