### ISSUE TITLE
Minimun gas price ignored

### ISSUE THREAD

**Issue by DomingoMr** [hyperledger/besu#5528] opened 2023-06-02 13:32 UTC
### Description
I want to set the minimum gas price to 0 so I can deploy smart contracts without problems.

### Acceptance Criteria
Parameter `--min-gas-price` not ignored

### Steps to Reproduce (Bug)
1. Use the command npx `quorum-dev-quickstart` to run a local besu network (`besu version` 22.10.3).
2. Deploy a smart contract to this local network.

**Expected behavior:**
To deploy the smart contract.

**Actual behavior:**
I get this error:

`ProviderError: Gas price below configured minimum gas price
    at HttpProvider.request (/home/domingo/token-erc20/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/domingo/token-erc20/node_modules/hardhat/src/internal/core/providers/accounts.ts:182:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EthersProviderWrapper.send (/home/domingo/token-erc20/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)`

If I look for Besus logs:

`{"timestamp":"2023-06-02T13:06:21,722","container":"39d421c9fa71","level":"INFO","thread":"main","class":"Besu","message":"Starting Besu","throwable":""}
{"timestamp":"2023-06-02T13:06:24,125","container":"39d421c9fa71","level":"WARN","thread":"main","class":"Besu","message":"--min-gas-price has been ignored because --miner-enabled was not defined on the command line.","throwable":""}
{"timestamp":"2023-06-02T13:06:27,088","container":"39d421c9fa71","level":"INFO","thread":"main","class":"Besu","message":"
`

As you can see, `--min-gas-price` is ignored. I tried to put in the config file this instruction `miner-enabled=true` but the network does not work.

**Frequency:**
Always I try to deploy a smart contract

### Versions (Add all that apply)
* Software version: [`22.10.3`]
* Java version: [`17`]
* OS Name & Version: [`WSL2`]

**Comment by non-fungible-nelson** [comment] 2023-06-05 21:41
@matthew1001 this is similar to the config cleanup you were working on? Or did I just recall you hitting the same hurdle 😅

**Comment by matthew1001** [comment] 2023-06-06 10:54
I certainly had to use a slightly odd combination of settings (the discord discussion is here -> https://discord.com/channels/905194001349627914/938504958909747250/1110826605447753759)

Setting `--min-gas-price` without also setting `--miner-enabled` caused Besu to issue the warning shown in the logs above. I did then set `--miner-enabled` but this gave a new error saying `--miner-coinbase` needed to be set.

@DomingoMr have you tried setting `--miner-coinbase` to see if that fixes the issue? I don't think `--miner-enabled` or `--miner-coinbase` are needed so they should just be ignored?

**Comment by matthew1001** [comment] 2023-06-06 10:57
I haven't raised an issue for the incorrect parameter validation yet, maybe it can be tracked under this issue? The (unrelated) config issue I've been looking at is some `TOML` files not accepted by Besu (https://github.com/hyperledger/besu/issues/5482). I'd be happy to help try and tidy up some of the validation issues being discussed here once `5482` is sorted.

**Comment by DomingoMr** [comment] 2023-06-06 16:16
Thnak you Matthew! I look forward to hearing from you

**Comment by matthew1001** [comment] 2023-06-08 13:11
I've just tried a fresh QBFT setup using a recent build from Besu `main` and it seems to be working fine with `--min-gas-price=0` set. I do still see the unexpected/erroneous warning about it being ignored:

`2023-06-08 13:51:21.529+01:00 | main | WARN  | Besu | --min-gas-price has been ignored because --miner-enabled was not defined on the command line.`

but I think that's just a misleading error message. I've tried issuing `eth_gasPrice` which is correctly returning `0x0` and I've successfully deployed a smart contract to the chain using hardhat.

This is the complete command line I've used to start the node:

`besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,TXPOOL,ADMIN,EEA,PRIV --host-allowlist="*" --tx-pool-max-size=2048 --rpc-http-cors-origins="all" --min-gas-price=0`

@DomingoMr could you see how your Besu command line args compare to mine please? And I would suggest removing `--miner-enabled` and `--miner-coinbase` if you still have them set.

**Comment by bengyles** [comment] 2023-06-12 09:33
@DomingoMr did you try this? it worked for me https://besu.hyperledger.org/en/stable/private-networks/how-to/configure/free-gas/#

**Comment by DomingoMr** [comment] 2023-06-12 17:11
Hi! @bengyles I tried that, but i cant set the `contractSizeLimit`, cause It does not appear on my config file. The rest does not work for me.

@matthew1001 I use the `quorum-dev-quickstart` that uses a docker-compose.yml. The command line used in this file is the following:
`/opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} ;`
If I try to add the `--min-gas-price`  instruction, is the same as if I add on the config file.

**Comment by alexcostars** [comment] 2023-06-13 00:43
I'm impacted by this error. I'm following this helm chart to deploy a besu component:

https://github.com/ConsenSys/quorum-kubernetes/blob/master/helm/charts/besu-node/values.yaml

This is the besu version:
```yaml
image:
  besu:
    repository: hyperledger/besu
    tag: 22.7.2
    pullPolicy: IfNotPresent
```

I'm using this script because is the official documentation, described here: https://besu.hyperledger.org/en/stable/private-networks/tutorials/kubernetes/

As I can see, probably the release 22.7.2 has a bug that causes this ignored param (because @matthew1001 tested it on the latest release and can't reproduce the message). Can I update this helm chart to Besu 23.4.1 by simply changing the `image.besu.tag` to 23.4.1?

**Comment by matthew1001** [comment] 2023-06-13 05:54
@alexcostars yes you should be able to just replace the tag on the image specification and set it to `23.4.1`

**Comment by DomingoMr** [comment] 2023-06-21 16:19
Hi! I have been working on this along this week and I have found a solution:

As u said @matthew1001, although logs show the warning `min-gas-price ignored`, the price is set to zero, but I still got the same error when deploying the contract.

What I had to do was to set `"zeroBaseFee": true` in the `genesis.json`,  inside "config", as @bengyles indicated (if u are using `quorum-dev-quickstart)`.  I tried to do it also with helm charts, but I do not know how to insert that line... so if anyone could help me with that, I would appreciate it. 

Anyway, I think the problem is solved.

**Comment by alexcostars** [comment] 2023-06-22 01:32
@matthew1001, our team are working to update the helm chart.

We are trying to set `zeroBaseFee`, as indicated by @DomingoMr, but is not working. Does anyone know how to configure the help chart to include this parameter (we are following this template: https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm/charts/besu-node)?

**Comment by matthew1001** [comment] 2023-06-22 09:11
@alexcostars I think at this step in the helm deploy you can set the `zeroBaseFee` in the genesis chart:

https://besu.hyperledger.org/en/stable/private-networks/tutorials/kubernetes/charts/#4-deploy-the-genesis-chart

e.g.

```
...
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      zeroBaseFee: true
      algorithm:
        consensus: qbft # choose from: ibft | qbft | raft | clique
...
```

Have you tried setting it there?

**Comment by DomingoMr** [comment] 2023-06-22 10:06
I did, but It did not work.

I tried to change also `/charts/besu-genesis/values`,  and `/charts/besu-genesis/templates/genesis-job-init.yaml` and did not work.

**Comment by matthew1001** [comment] 2023-06-27 15:44
@alexcostars I might suggest raising a separate issue to track helm (as opposed to quickstart, which this issue was originally opened for). Is that OK with you?

**Comment by DomingoMr** [comment] 2023-06-28 13:22
@alexcostars Try to set the besu tag version to 23.4.1 and `zeroBaseFee` instruction should work

**Comment by matthew1001** [comment] 2023-07-11 08:03
I'm closing this as https://github.com/hyperledger/besu/pull/5669 has been merged which tidies up the warning messages around mining options when anything other than an `ethash` network is being used (so the `--min-gas-price has been ignored because --miner-enabled was not defined on the command line.` warning shouldn't show up when using QBFT/IBFT/clique networks) and https://github.com/Consensys/quorum-dev-quickstart/pull/258 has also been merged (which makes the quickstart work as a free gas chain).

If there are still issues with the helm charts and not being able to set `zeroBaseFee` let's open a new issue for that.

**Closed by matthew1001** 2023-07-11 08:03 UTC
Labels: non mainnet (private networks)
