### ISSUE TITLE
Fast sync fails with Max Retries reached and backward sync keeps waiting for pre-conditions

### ISSUE THREAD

**Issue by ricardolyn** [hyperledger/besu#3996] opened 2022-06-21 08:59 UTC
### Description

When setting up a Besu node to sync with the Kiln network and connected to a Lighthouse Beacon, we keep having issues with syncing (using FAST sync mode) and finding peers.

### Steps to Reproduce (Bug)
1. Configure a Besu node for Kiln
2. Configure a Lighthouse beacon for Kiln, and set the Execution client as the Besu node.
3. Start both services

**Expected behavior:** [What you expect to happen]

Both Lighthouse and Besu are able to sync. 

**Actual behavior:** [What actually happens]

Lighthouse gets synced and connected to Besu.
However, keeps showing errors that Besu is Far behind (even if besu showed logs that confirmed the control from Beacon).

**Frequency:** 100% of times on this setup.

### Versions (Add all that apply)
* Image version: `fab10/besu:22.4.3-SNAPSHOT` (running on kubernetes)

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
```
       --data-path=/data                                                                                                                                                                                        │
│       --host-allowlist=*                                                                                                                                                                                       │
│       --network=kiln                                                                                                                                                                                           │
│       --rpc-http-enabled=true                                                                                                                                                                                  │
│       --rpc-http-host=0.0.0.0                                                                                                                                                                                  │
│       --rpc-http-cors-origins=*                                                                                                                                                                                │
│       --rpc-http-port=8545                                                                                                                                                                                     │
│       --rpc-http-max-active-connections=300                                                                                                                                                                    │
│       --rpc-ws-enabled=true                                                                                                                                                                                    │
│       --rpc-ws-host=0.0.0.0                                                                                                                                                                                    │
│       --rpc-ws-port=8546                                                                                                                                                                                       │
│       --engine-host-allowlist=*                                                                                                                                                                                │
│       --engine-rpc-http-port=8550                                                                                                                                                                              │
│       --engine-jwt-enabled=true                                                                                                                                                                                │
│       --engine-jwt-secret=/opt/secrets/jwtsecret.hex                                                                                                                                                           │
│       --override-genesis-config=terminalTotalDifficulty=20000000000000                                                                                                                                         │
│       --data-storage-format=BONSAI                                                                                                                                                                             │
│       --sync-mode=FAST                                                                                                                                                                                         │
│       --fast-sync-min-peers=1                                                                                                                                                                                  │
│       --rpc-http-enabled=true                                                                                                                                                                                  │
│       --rpc-http-api=ETH,ADMIN,NET,WEB3
```

### Logs

1. **Logs with errors on fast sync:**

```
 2022-06-20 14:39:00.618+00:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xe2c33c7b8a5c0ed167... PeerReputation 100, validated? true, disconnected? false at b │
│ 2022-06-20 14:39:03.857+00:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xe2c33c7b8a5c0ed167... PeerReputation 100, validated? true, disconnected? false at b │
│ 2022-06-20 14:39:06.946+00:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xe2c33c7b8a5c0ed167... PeerReputation 100, validated? true, disconnected? false at b │
│ 2022-06-20 14:39:11.938+00:00 | nioEventLoopGroup-3-1 | INFO  | FastSyncDownloader | Re-pivoting to newer block.                                                                                               │
│ 2022-06-20 14:39:11.938+00:00 | nioEventLoopGroup-3-1 | INFO  | FastSyncDownloader | Starting sync.                                                                                                            │
│ 2022-06-20 14:39:11.938+00:00 | nioEventLoopGroup-3-1 | INFO  | FastSyncDownloader | Clearing bonsai flat account db                                                                                           │
│ 2022-06-20 14:39:12.065+00:00 | nioEventLoopGroup-3-1 | INFO  | TransitionPivotSelector | A finalized block is present, use it as pivot                                                                        │
│ 2022-06-20 14:39:12.066+00:00 | nioEventLoopGroup-3-1 | INFO  | PivotSelectorFromFinalizedBlock | Returning finalized block hash as pivot: 0xde6cad12a72f83e8f24fd936a49bef5fa67ebdee68100aedd58b4d5463613b1a  │
│ 2022-06-20 14:39:12.069+00:00 | nioEventLoopGroup-3-1 | INFO  | AbstractRetryingPeerTask | No useful peer found, checking remaining current peers for usefulness: 0                                            │
│ 2022-06-20 14:39:17.070+00:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No useful peer found, checking remaining current peers for usefulness: 0                                             │
│ 2022-06-20 14:39:22.070+00:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No useful peer found, checking remaining current peers for usefulness: 0                                             │
│ 2022-06-20 14:39:27.073+00:00 | EthScheduler-Timer-0 | ERROR | FastSyncDownloader | Encountered an unexpected error during fast sync. Restarting fast sync in PT5S seconds.                                    │
│ java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED                                                    │
│     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)                                                                                                            │
│     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)                                                                                                          │
│     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)                                                                                                           │
│     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)                                                                                                               │
│     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)                                                                                                     │
│     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:85)                                                                                   │
│     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)                                                                                               │
│     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractRetryingPeerTask.lambda$handleTaskError$1(AbstractRetryingPeerTask.java:126)                                                                     │
│     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)                                                                                                            │
│     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)                                                                                                    │
│     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)                                                                                                               │
│     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)                                                                                                     │
│     at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$failAfterTimeout$11(EthScheduler.java:278)                                                                                                │
│     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                                      │
│     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)                                                                                │
│     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                               │
│     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                               │
│     at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                                         │
│ Caused by: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED                                                                                   │
│     ... 13 more                                                                                                                                                                                                │
│ 2022-06-20 14:39:32.075+00:00 | EthScheduler-Timer-0 | INFO  | FastSyncDownloader | Starting sync.                                                                                                             │
│ 2022-06-20 14:39:32.075+00:00 | EthScheduler-Timer-0 | INFO  | FastSyncDownloader | Clearing bonsai flat account db                                                                                            │
│ 2022-06-20 14:39:32.193+00:00 | EthScheduler-Timer-0 | INFO  | WaitForPeersTask | Waiting for 1 total peers to connect. 0 peers currently connected.                                                           │
│ 2022-06-20 14:40:37.465+00:00 | Thread-13 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:42:37.466+00:00 | Thread-14 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:43:24.990+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-20 14:44:37.467+00:00 | Thread-15 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:46:37.467+00:00 | Thread-16 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:48:37.468+00:00 | Thread-17 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:49:48.736+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-20 14:50:37.469+00:00 | Thread-18 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:52:37.470+00:00 | Thread-19 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:54:37.471+00:00 | Thread-20 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:56:12.569+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-20 14:56:37.472+00:00 | Thread-21 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 14:58:37.473+00:00 | Thread-22 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 15:00:37.474+00:00 | Thread-23 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                         │
│ 2022-06-20 15:02:36.715+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577
```

2. **Same issue after 12h hours:**

```
│ 2022-06-21 08:06:36.761+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:06:37.851+00:00 | Thread-536 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:08:37.852+00:00 | Thread-537 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:10:37.853+00:00 | Thread-538 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:12:37.853+00:00 | Thread-539 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:13:00.932+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:14:37.854+00:00 | Thread-540 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:16:37.855+00:00 | Thread-541 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:18:37.855+00:00 | Thread-542 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:19:24.808+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:20:37.856+00:00 | Thread-543 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:22:37.856+00:00 | Thread-544 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:24:37.857+00:00 | Thread-545 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:25:48.575+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:26:37.858+00:00 | Thread-546 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:28:37.858+00:00 | Thread-547 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:30:37.859+00:00 | Thread-548 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:32:12.658+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:32:37.860+00:00 | Thread-549 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:34:37.860+00:00 | Thread-550 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:36:37.861+00:00 | Thread-551 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:38:36.787+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:38:37.862+00:00 | Thread-552 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:40:37.862+00:00 | Thread-553 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:42:37.863+00:00 | Thread-554 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:44:37.864+00:00 | Thread-555 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:45:00.576+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:46:37.864+00:00 | Thread-556 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:48:37.865+00:00 | Thread-557 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:50:37.866+00:00 | Thread-558 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:51:24.804+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:52:37.867+00:00 | Thread-559 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:54:37.867+00:00 | Thread-560 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:56:37.868+00:00 | Thread-561 | INFO  | BackwardSyncContext | Waiting for preconditions...                                                                                                        │
│ 2022-06-21 08:57:48.839+00:00 | vert.x-worker-thread-0 | INFO  | EthProtocolManager | disconnecting peers with total difficulty over 20001479054577                                                            │
│ 2022-06-21 08:58:37.869+00:00 | Thread-562 | INFO  | BackwardSyncContext | Waiting for preconditions...
```
and Logs from lighthouse:

```
│ Jun 21 08:57:48.585 INFO New block received                      root: 0xa19595f352018856e6d42467b9a530a620c13ac4dc0a0d528fc9cebe880582c9, slot: 732864                                                        │
│ Jun 21 08:57:54.000 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x48e8703b1e02d25afc619d1bbfbb0d19caaa192d128134ae6e8d22fdc701f7eb), service: slot_notifier          │
│ Jun 21 08:57:54.001 INFO Synced                                  slot: 732864, block: 0xa195…82c9, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x48e8…f7eb (unverified), pee │
│ Jun 21 08:58:00.624 INFO New block received                      root: 0xc4ef6c18201443621ec8ab32985e4aaa36f5cd68a2cce2eb095398d89fc431af, slot: 732865                                                        │
│ Jun 21 08:58:06.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x1c6591b7627a307aeec7a15ea40e7725bcd5ea8b00c5b1907a08e13ae60272d5), service: slot_notifier          │
│ Jun 21 08:58:06.001 INFO Synced                                  slot: 732865, block: 0xc4ef…31af, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x1c65…72d5 (unverified), pee │
│ Jun 21 08:58:18.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x1c6591b7627a307aeec7a15ea40e7725bcd5ea8b00c5b1907a08e13ae60272d5), service: slot_notifier          │
│ Jun 21 08:58:18.001 INFO Synced                                  slot: 732866, block:    …  empty, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x1c65…72d5 (unverified), pee │
│ Jun 21 08:58:24.197 INFO New block received                      root: 0xb73db67f143c486890d95d2929431c3bb67248c81dfb6316a29fde7f296fdb3d, slot: 732867                                                        │
│ Jun 21 08:58:30.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x3ace7a3a2fd43e2686cfac48d568357aebe8dc63317c59da90cf6b015fffbf0c), service: slot_notifier          │
│ Jun 21 08:58:30.001 INFO Synced                                  slot: 732867, block: 0xb73d…db3d, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x3ace…bf0c (unverified), pee │
│ Jun 21 08:58:37.671 INFO New block received                      root: 0xdc93885ce79a92edae1754305039cba47f28186ce005900587b700d68d6097be, slot: 732868                                                        │
│ Jun 21 08:58:42.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x5dbf8712fab6ab4a99388b184950ebbe26a8d4f4a544af131001623ee2acdfc4), service: slot_notifier          │
│ Jun 21 08:58:42.001 INFO Synced                                  slot: 732868, block: 0xdc93…97be, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x5dbf…dfc4 (unverified), pee │
│ Jun 21 08:58:48.217 INFO New block received                      root: 0x13d84c4bd54e4377b784c65a6999f2dae3aef57ffed34081c43143fc847b4e30, slot: 732869                                                        │
│ Jun 21 08:58:53.727 ERRO Error fetching block for peer           error: BlockHashMissingFromExecutionLayer(ExecutionBlockHash(0xf23681bc9b1587fd33113797fd35dd353ca5dee8436662e706ded0017af000ad)), block_root │
│ Jun 21 08:58:54.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x48c3fd2228ebc2df49f1f04a72f4d5f8cae329680023ffce1f4270abda19f49e), service: slot_notifier          │
│ Jun 21 08:58:54.001 INFO Synced                                  slot: 732869, block: 0x13d8…4e30, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x48c3…f49e (unverified), pee │
│ Jun 21 08:58:54.636 ERRO Error fetching block for peer           error: BlockHashMissingFromExecutionLayer(ExecutionBlockHash(0x6cb7f7287d181ffa93ac08db4ab1bc7f5f8c8fe1f6239a30be060bfe0aa3e8a9)), block_root │
│ Jun 21 08:58:55.231 ERRO Error fetching block for peer           error: BlockHashMissingFromExecutionLayer(ExecutionBlockHash(0x09986e0a44f3a7387f79fad0c8fcffe81e4e8bd0a688b5a292ea32470d89f908)), block_root │
│ Jun 21 08:59:00.153 INFO New block received                      root: 0x84f3e46d78a69d88e68081b220982281b334122ce1b710b4b35f166d636053f7, slot: 732870                                                        │
│ Jun 21 08:59:06.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0x585b5bddd510467e6a6100e7fb555d5c1e005b42471355a80833f113fefdb2d4), service: slot_notifier          │
│ Jun 21 08:59:06.001 INFO Synced                                  slot: 732870, block: 0x84f3…53f7, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0x585b…b2d4 (unverified), pee │
│ Jun 21 08:59:12.254 INFO New block received                      root: 0x3eabcbd0f0fa52e09b8611a9419845d019d6ad31c9fcf8f9ddc8b3952222b041, slot: 732871                                                        │
│ Jun 21 08:59:18.001 WARN Head execution payload is unverified    execution_block_hash: ExecutionBlockHash(0xe002453629192b9ed8fa8f90586038f03c91f4e94d79697ef2c30480bb76d843), service: slot_notifier          │
│ Jun 21 08:59:18.001 INFO Synced                                  slot: 732871, block: 0x3eab…b041, epoch: 22902, finalized_epoch: 22900, finalized_root: 0x7c5d…c37f, exec_hash: 0xe002…d843 (unverified), pee │
│ Jun 21 08:59:24.167 INFO New block received                      root: 0xe4994f031b02975573539f8242ec6f902d6dd9eeccedce8feb845ba7d44b3eb3, slot: 732872
```

**Comment by Gabriel-Trintinalia** [comment] 2022-07-12 07:38
Hi Ricardo, 

I was not able to replicate this issue using the latest (22.4.4) version of Besu with the latest unstable version of lighthouse. I was able to get them to sync. The message (FarBehind) on LH appeared until Besu finished sync 

Initially, I also could not find the message: 

`INFO  disconnecting peers with total difficulty over. `
 
Looking into the code, it seems that the code where best got stuck was introduced by the PR:  https://github.com/hyperledger/besu/pull/3944. 

I believe that the issue was caused by the block: 
https://github.com/jflo/besu/blob/e8674bdea9cd885c66be52c63bca78d68479a940/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java#L394

This code, however, was reverted by the PR https://github.com/hyperledger/besu/pull/3978. 

Would be able to tested it again with the latest stable version of Besu?

**Comment by Gabriel-Trintinalia** [comment] 2022-07-13 22:41
Closing this one since the issue seems to be caused by an unstable code that got removed from Besu

**Closed** 2022-07-13 23:42 UTC
Labels: bug, TeamRevenant, mainnet

**Comment by ricardolyn** [comment] 2022-07-19 08:36
thanks. @Gabriel-Trintinalia which version fixed this issue?

**Comment by ricardolyn** [comment] 2022-07-19 08:52
thanks @Gabriel-Trintinalia
