### ISSUE TITLE
Error: Block body not valid

### ISSUE THREAD

**Issue by estensen** [hyperledger/besu#4450] opened 2022-09-27 19:51 UTC
Mainnet
v22.7.4
Checkpoint sync
Bonsai
Paired with Lighthouse

I'm used to errors being actionable. But is this just nothing to worry about?

```
2022-09-27 21:14:25.151+02:00 | vert.x-worker-thread-0 | WARN  | MainnetBlockBodyValidator | Invalid block: receipts root mismatch (expected=0x7a7983992cbc8e1acdec6ac67219df48a6ebb79b655f88ac3c78169b4e97dfc0, actual=0xd2159ad55c1991ff1ecbc53dade86253293142d949e1eeb7a9fb9a33036a14ee)
2022-09-27 21:14:25.152+02:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Block body not valid. Block 15626706 (0x55b8d3a7294a8028d2fadc350aeaa7760630c4c4a81a32706885543625c27112)
2022-09-27 21:14:25.152+02:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 15626706, hash: 0x55b8d3a7294a8028d2fadc350aeaa7760630c4c4a81a32706885543625c27112, parentHash: 0x45e364d853ddd09a5569811e87394e337b7e6527cb556a048f7705f119966a4b, latestValidHash: 0x45e364d853ddd09a5569811e87394e337b7e6527cb556a048f7705f119966a4b, status: INVALID, validationError: Block body not valid
2022-09-27 21:14:38.087+02:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Imported #15,626,706 / 244 tx / base fee 15.44 gwei / 24,485,449 (81.6%) gas / (0x8f5a3dba95f69757c3b634acca3904ff07552a39f299f654e7f0d958de3f8b2b) in 1.153s. Peers: 25
```

**Comment by daniellehrner** [comment] 2022-09-28 08:57
One of the mev-boost relays has proposed several invalid blocks. See here: https://twitter.com/terencechain/status/1574892822871756803?s=20&t=NeMHZ9hXROB-SfuWpZwcXA

The error that you are seeing means that Besu has correctly identified them as invalid and is sending this response to the CL.

I'll close this issue, as Besu is working as intended. Please feel free to reopen, if there is another issue.

**Comment by estensen** [comment] 2022-09-28 09:01
I think it would be nice to not log this as an error then, since it's not a client error. Errors are scary.

**Comment by daniellehrner** [comment] 2022-09-28 10:10
I talked with my team and we agree with your reasoning. I'll change it to info

**Closed** 2022-10-04 10:07 UTC
Labels: enhancement, mainnet
